# (PART\*) LIỄU PHÀM TỨ HUẤN {-}

# Tự lập số mạng {- #tu-lap-so-mang}

Tôi thuở nhỏ đã sớm mất cha.^[Viên Liễu Phàm sinh năm 1533 và mất năm 1606.
Bản văn này ban đầu được ông viết ra để dạy con,
nên một số đại từ nhân xưng được dùng tương ứng
trong quan hệ cha con. Khi chuyển dịch chúng tôi đã
có một vài chỉnh sửa nhỏ về cách xưng hô để thích
hợp hơn với đa số độc giả, vì xét thấy việc này không
làm thay đổi ý chính của bản văn.] Mẹ
tôi bảo tôi từ bỏ đường công danh
khoa cử để theo học nghề thuốc, vì cho rằng
như thế có thể vừa tự nuôi sống lại cũng có
thể cứu giúp người khác. Hơn nữa, việc tôi
theo học thành tựu một nghề để có thể lưu
danh ở đời cũng là tâm nguyện từ trước đây
của cha tôi.

Sau đó, có lần tôi đến chùa Từ Vân tình cờ
gặp một cụ già cốt cách phương phi, râu dài
tóc bạc, tướng mạo dường như tiên ông. Khi
tôi đến lễ chào cung kính, cụ già bảo tôi: “Con
là người trong đường quan tước, ngày sau ắt
sẽ học lên cao, sao nay con chẳng lo việc đọc
sách?”

Tôi liền nói rõ nguyên nhân. Ông cụ bảo:
“Ta họ Khổng, người Vân Nam, được chân
truyền thuật toán số Hoàng Cực của Thiệu
tử,^[Tức Thiệu Ung hay Thiệu Khang Tiết, sinh năm 1011,
mất năm 1077, là một học giả uyên bác, nghiên cứu
Chu Dịch lâu năm, có để lại nhiều tác phẩm như
Mai hoa dịch số, Hoàng cực kinh thế, Quan vật nội
thiên, Ngư tiều vấn đối, Nhượng Sơn tập, Tử Bá Ôn
biệt truyện...] theo mạng số ắt rồi sau sẽ truyền thuật
này cho con.”

Tôi liền mời cụ già về nhà, đem mọi việc
trình lên với mẹ. Về sau, xem xét những điều
cụ già họ Khổng đã tiên đoán cho tôi đều dần
dần ứng nghiệm. Sau khi gặp cụ Khổng, tôi
khởi ý quay lại theo việc học hành khoa cử.

Cụ Khổng lại đoán trước cho tôi về đường
khoa cử, nói rằng khi mới đi học, thi lần đầu
ở huyện sẽ đỗ thứ 14, thi ở phủ sẽ đỗ thứ 71,
thi ở tỉnh sẽ đỗ thứ 9. Sau tôi đi thi, ở cả ba
nơi đều đỗ đạt đúng như thứ hạng ông ấy đã
dự đoán.

Cụ Khổng lại đoán số mạng trọn đời cho
tôi, cho biết đến năm ấy sẽ thi đỗ thứ hạng
như thế, sang năm ấy sẽ được chọn làm lẫm
sinh,^[ Lẫm sinh: người học trò được nhận học bổng (bằng
lúa gạo), do triều đình chu cấp.] sang năm ấy sẽ được chọn làm cống
sinh,^[ Cống sinh: nho sinh giỏi, được chọn lên kinh đô theo
học để chuẩn bị cho kỳ thi tại kinh đô.] lại sau đến năm ấy sẽ được bổ làm Tri
huyện ở tỉnh Tứ Xuyên, làm quan được 2 năm
rưỡi^[Chúng tôi y theo bản khắc trong An Sĩ toàn thư, có
bản khác khắc là 3 năm rưỡi (三年半).] ắt sẽ cáo quan về quê, cho đến năm 53
tuổi, vào giờ Sửu, ngày 14 tháng 8 sẽ mất tại
nhà, chỉ tiếc là không có con. Tôi ghi chép đầy
đủ những điều ấy, luôn nhớ kỹ trong lòng.

Từ đó về sau, mỗi lần dự thi kết quả đều
không ra ngoài những dự đoán của cụ già
họ Khổng. Riêng có một lần, cụ Khổng đoán
rằng thời gian tôi làm lẫm sinh phải nhận đủ
91 thạch 5 đấu gạo^[Các đơn vị đo lường thời xưa. Mỗi thạch bằng khoảng
100 lít; 10 đấu bằng một thạch.
] mới được lên cống sinh,
nhưng khi số gạo nhận được của tôi vừa hơn
70 thạch thì tôn sư họ Đồ đã thông qua việc
chọn tôi làm cống sinh, do đó tôi hơi có chút
ngờ vực về sự tiên đoán của cụ. Chẳng ngờ
sau đó có vị quan tạm quyền họ Dương [vừa
chuyển đến] lại bác bỏ việc này, nên phải đợi
đến năm Đinh Mão^[Tức là năm 1567.] tôi mới được phê chuẩn
làm cống sinh. Vào lúc ấy tính lại, quả nhiên
tôi đã nhận được vừa đúng 91 thạch 5 đấu
gạo. Tôi nhân việc đó lại càng tin chắc rằng
sự đời thăng trầm đều do số mạng, dù nhanh
hay chậm cũng đều có thời hạn định trước, vì
thế mà [đối với hết thảy mọi việc] trong lòng
tôi trở nên lạnh nhạt không còn mong cầu gì
nữa.

Sau khi được lên cống sinh, tôi phải về
kinh thành Yên đô^[Yên đô: tên gọi cũ của Bắc Kinh.] theo học. Ở kinh đô được
một năm, tôi thường ngồi yên tĩnh suốt ngày,
chẳng đọc sách vở gì. Sau có dịp quay về chơi
ở Nam Ung trong lúc còn chưa vào nhập học,
tôi liền đến viếng thăm Thiền sư Vân Cốc
trong núi Thê Hà.^[Thiền sư pháp danh Pháp Hội, hiệu Vân Cốc, sinh
năm 1500 (niên hiệu Hoằng Trị thứ 13 đời Minh
Hiếu Tông). Cuộc gặp gỡ này diễn ra vào năm 1569.] Tôi cùng Thiền sư ngồi đối
diện trong tịnh thất, trải qua suốt ba ngày
ba đêm dường như không chớp mắt. Thiền
sư nói: “Người đời sở dĩ không trở thành bậc
thánh nhân, đều là do vọng niệm nối nhau
sinh khởi trói buộc. Nay ông ngồi suốt ba
ngày không khởi sinh vọng niệm là do đâu?”

Tôi đáp: “Trước đây có tiên sinh họ Khổng
từng xem số mạng cho con. Con xét thấy rằng
mọi sự vinh nhục, sống chết ở đời đều do số
mạng định sẵn, dù có muốn vọng cầu điều
này điều nọ cũng đều không thể được [nên
con chẳng nghĩ gì cả].”

Thiền sư Vân Cốc bật cười nói: “Ta ngỡ ông
là bậc hào kiệt xuất chúng, hóa ra chỉ là một
kẻ tầm thường.”

Tôi không hiểu, thưa hỏi. Thiền sư liền
nói: “Con người khi chưa đạt được đến mức
vô tâm, rốt lại đều bị những lẽ âm dương toán
số kia trói buộc, sao có thể nói là không có
số mạng? Nhưng chỉ những kẻ tầm thường
mới có số mạng mà thôi. Bậc đại hiền thì số
mạng không nhất định, mà với kẻ đại gian ác
số mạng cũng không thể nhất định. Ông từ
20 năm nay bị những lẽ đoán định của người
khác trói buộc, không tự thay đổi được mảy
may nào, như thế chẳng phải là tầm thường
lắm sao?”

Tôi liền hỏi: “Vậy ra số mạng có thể tránh
được sao?”

Thiền sư đáp: “Số mạng là do chính mình
tạo ra, phước đức do chính mình cầu mà được.
Trong sách vở Nho gia có nhiều chỗ dạy rõ
điều đó. Kinh Phật lại có nói: _‘Cầu công danh
ắt được công danh, cầu sống lâu ắt được sống
lâu, cầu con trai, con gái, ắt có con trai, con
gái...’_ Nói dối là giới cấm quan trọng mà đức
Phật Thích-ca đã chế định, lẽ nào chư Phật,
Bồ Tát lại nói dối để lừa gạt người đời hay
sao?”

Tôi nghe vậy rồi liền hỏi tiếp: “Mạnh tử có
nói rằng: _‘Cầu ắt sẽ được, ấy là cầu nơi chính
mình.’_ Đạo đức, nhân nghĩa [là ở nơi chính
mình] nên có thể gắng sức cầu được, còn như
công danh phú quý [vốn không ở nơi chính
mình] làm sao có thể cầu được?”

Thiền sư Vân Cốc nói: “Lời Mạnh tử vốn
không sai, chỉ do ông tự hiểu sai thôi. Ông
không nghe đức Lục tổ có dạy rằng: ‘Hết
thảy ruộng phước vốn chẳng xa lìa gang tấc,
từ trong tâm này mà cầu thì mọi tâm niệm
đều thông suốt.’ [Mạnh tử nói] _‘Cầu nơi chính
mình’_ đó không chỉ là riêng được đạo đức
nhân nghĩa, mà cũng được cả công danh phú
quý, trong ngoài đều được cả. Cầu như vậy
hữu ích là vì cầu được. Nếu không quay về
cứu xét nơi tự thân mình, chỉ biết hướng theo
ngoại cảnh dong ruổi tìm cầu thì mong cầu là
một việc mà được hay không lại còn phải tùy
vào số mạng, như vậy có khi trong ngoài đều
mất cả [vì cầu mà không được]. Cầu như vậy
ắt là vô ích.”

Thiền sư lại hỏi: “Họ Khổng đoán vận
mạng suốt đời của ông như thế nào?”

Tôi thật lòng đem hết mọi việc kể ra.
Thiền sư liền nói: “Ông hãy tự xét mình xem
có xứng đáng đỗ đạt đại khoa, có xứng đáng
được sinh con nối dõi chăng?”

Tôi suy nghĩ hồi lâu rồi đáp: “Thật không
xứng đáng. Những người đỗ đạt đại khoa nói
chung đều có tướng phước đức sâu dày. Con
vốn phước mỏng, lại không thể tích lũy công
đức thiện hạnh để làm nền tảng cho phước
đức sâu dày. Con lại không nhẫn chịu được
những sự phiền toái khổ nhọc, không thể bao
dung chịu đựng người khác, đôi khi lại cậy
vào tài trí của mình mà lấn áp người, tính
tình bộc trực nghĩ sao làm vậy, thường xem
nhẹ lời nói, hay luận bàn những chuyện vô
bổ, hết thảy đều là những biểu hiện phước
mỏng đức bạc, làm sao có thể đỗ đạt đại khoa?

“Đất bùn dơ ẩm ướt thường nhiều vật
sống, chỗ nước trong vắt thường không có cá,
mà tánh con lại ưa thích sự trong sạch thanh
khiết [thái quá]. Tánh khí ôn hòa có thể nuôi
dưỡng vạn vật, mà tánh con lại thường nóng
nảy sân hận. Luyến ái là cội nguồn của sự
tiếp nối sinh sản, không quan tâm đến người
khác là căn bản của sự không nuôi dưỡng, mà
tánh con xem trọng danh tiết của riêng mình,
thường không thể quên mình giúp người; con
lại thường nói nhiều hao tổn khí lực, thích
ngồi lặng suốt đêm dài không ngủ, không
biết giữ gìn nguyên khí tinh thần. Hết thảy
những điều ấy đều là nguyên nhân không thể
có con. Ngoài ra còn có biết bao điều lỗi lầm
xấu ác nữa, thật không thể nói hết!”

Thiền sư Vân Cốc nói: “Nào chỉ riêng vấn
đề khoa bảng [như ông vừa nói đó]! Người đời
thụ hưởng tài sản ngàn vàng, ắt phải là người
đáng hưởng ngàn vàng; kẻ nhận tài sản trăm
lượng, ắt phải là kẻ đáng nhận trăm lượng.
Người chịu chết đói, ắt phải là người đáng
phải chết đói. [Nói là mệnh] trời, bất quá chỉ
là do nơi nhân quả nghiệp báo riêng của mỗi
người mà thành, vốn chưa từng có chút thêm
bớt nào [gọi là ý trời trong đó cả].

“Đến như việc sinh con cái, như người có
phước đức truyền được trăm đời, ắt sẽ sinh
được con cháu truyền đủ trăm đời; người có
phước đức truyền được mười đời, ắt sẽ sinh
được con cháu truyền đủ mười đời; người có
phước đức truyền được ba đời, hai đời, ắt sẽ
sinh được con cháu truyền đủ ba đời, hai đời;
cho đến người dứt hẳn không có con cháu, ấy
là do phước đức hết sức mỏng manh vậy. Nay
ông đã biết rõ những điều sai trái [của mình],
những điều đã khiến ông không thể đỗ đạt đại
khoa, không thể sinh con nối dõi, vậy ông phải
hết lòng hối cải, tự thay đổi, nhất thiết phải
lo tu nhân tích đức, nhất thiết phải bao dung
rộng lượng với người, nhất thiết phải hòa nhã
thương yêu kẻ khác, nhất thiết phải biết gìn
giữ bảo dưỡng tinh thần.

“Hết thảy những việc từng làm trước đây,
xem như đã chết từ hôm qua. Hết thảy những
việc từ nay về sau, xem như mới được sinh
ra từ hôm nay. Đó chính là ý nghĩa của việc
làm sống lại thân này. Thân thể bằng xương
thịt này tất nhiên đã có nghiệp quả định sẵn,
nhưng cái thân tinh thần nhân nghĩa đạo
đức, lẽ nào lại không thể [tu dưỡng] để thay
đổi được sao?

“Sách Thượng thư, thiên Thái giáp có nói:
_‘Tai họa do trời giáng xuống còn có thể tránh
né, tai họa do chính mình tạo ra thì không
còn đường sống.’_ Kinh Thi nói: _“Lời nói việc
làm thường hợp đạo trời, ấy là tự mình cầu
được nhiều phước đức.”_ Khổng tiên sinh đoán
rằng ông không đỗ đại khoa, không có con nối
dõi, đó là _‘tai họa do trời giáng xuống’_ , cho
nên _‘còn có thể tránh né’_. Nay ông nỗ lực làm
thiện, rộng tích chứa âm đức, đó là tự mình
tạo ra phước đức, lẽ nào lại có thể không được
hưởng [những phước đức ấy] hay sao?

“Kinh Dịch nói rằng: _‘Bậc quân tử hướng về
điều lành, tránh đi điều dữ.’_ Nếu nói mệnh trời
là không thể thay đổi, vậy điều lành làm sao
có thể hướng về, điều dữ làm sao có thể tránh
đi? Lại cũng trong Kinh Dịch, quẻ Khôn, ngay
nơi phần ý nghĩa mở đầu đã nói rằng: _‘Nhà
làm việc thiện ắt có niềm vui, nhà làm việc ác
ắt gặp tai ương.’_ Nay ông đã có thể tin hiểu
được chưa?”

Tôi tin nhận lời Thiền sư, lễ bái xin học
làm theo. Nhân đó liền đem hết thảy những
điều lỗi lầm xấu ác đã qua, đối trước bàn thờ
Phật mà nêu rõ, viết thành một bản sớ dài
trình bày đầy đủ tất cả trong đó, cầu xin sám
hối. Sau đó tôi phát tâm cầu thi cử đỗ đạt,
nguyện làm đủ 3.000 điều thiện để báo đáp
ân đức của tổ tiên, trời đất.

Thiền sư lại lấy ra một bản sách “Công quá
cách” đưa cho tôi xem, dạy tôi [học làm theo
đó], ghi chép tất cả việc làm hằng ngày, nếu
là điều thiện thì cộng thêm vào, nếu là điều
xấu ác thì trừ bớt đi. Thiền sư lại dạy tôi trì
tụng thần chú Chuẩn Đề, qua một thời gian
ắt có sự linh nghiệm. Thiền sư bảo tôi rằng:

“Những người vẽ bùa chú thường nói:
‘Vẽ bùa không đúng cách sẽ bị quỷ thần
cười chê.’ [Trong việc vẽ bùa] có một phép bí
truyền, chẳng qua đó chỉ là không khởi lên
vọng niệm. Khi cầm bút vẽ, việc trước tiên
là phải buông bỏ hết thảy mọi ý niệm [duyên
theo trần cảnh]. Từ chỗ trong tâm không
chút động niệm như thế mới phóng bút điểm
xuống, gọi là tạo dựng nền tảng không phân
biệt. Từ một điểm làm nền tảng đó, cho đến
khi vung bút vẽ xong lá bùa, nếu trong tâm
tuyệt nhiên không khởi vọng niệm thì lá bùa
ấy sẽ linh nghiệm.

“Cho đến việc cầu đảo mệnh trời, điểm cốt
yếu vẫn là phải từ nơi tâm niệm rỗng rang
không động niệm như thế mà tạo ra sự cảm
ứng thay đổi. Mạnh tử khi bàn về cái học Lập
mệnh có nói: *"Chết yểu với sống lâu vốn chẳng
phải hai điều khác nhau."*^[Mạnh tử, chương Tận tâm, phần thượng. Trọn câu
này là: “夭壽不貳，修身以俟之，所以立命也。”
(Yểu thọ bất nhị, tu thân dĩ sĩ chi, sở dĩ lập mệnh dã. - Chết yểu với sống lâu vốn chẳng phải hai điều khác
nhau, hãy tu sửa tự thân để chờ đón mọi việc, như thế
gọi là tự lập số mệnh.)
] Phân tích đến chỗ
sâu xa tinh tế thì _dư thừa_ với _thiếu thốn_ vốn
cũng chẳng phải hai điều khác nhau, nhân
đó mới có thể tạo ra số mạng giàu, nghèo; _bế
tắc_ với _hanh thông_ vốn cũng chẳng phải hai
điều khác nhau, nhân đó mới có thể tạo ra số
mạng sang, hèn; _chết yểu_ với _sống lâu_ vốn
cũng chẳng phải hai điều khác nhau, nhân đó
mới có thể tạo ra số mạng sống, chết.

“Người đời lấy chuyện sống chết là quan
trọng, cho nên [Mạnh tử chỉ] nói _“chết yểu,
sống lâu”_ , nhưng kỳ thật hết thảy những
chuyện vừa lòng hay nghịch ý [trong cuộc
đời] cũng đều cùng một nguyên lý như vậy.

“Cho đến câu _‘hãy tu sửa tự thân để chờ
đón mọi việc’_ , đó là nói việc làm thiện tích
đức có thể chuyển đổi mệnh trời. Nói _‘tu sửa
tự thân’_ , đó là tự thân mình có điều gì lỗi lầm
xấu ác đều phải đối trị, dứt trừ đi. Nói _‘chờ
đón’_ , [đó là sẵn sàng đợi việc xảy ra], nhưng
nếu trong lòng có chút mong cầu điều tốt đẹp
hay nôn nao chờ đợi đều phải dứt sạch đi. Đạt
đến mức như thế, đó là tự tạo ra được cảnh
giới nguyên sơ không động niệm, đó chính là
cái học chân thật.

“Ông tuy chưa thể đạt được tâm thức rỗng
rang không vọng niệm [như thế], nhưng nếu
có thể trì tụng thần chú Chuẩn Đề, không
nghĩ nhớ, không tính đếm, không để gián
đoạn, khi được thuần thục rồi thì trong chỗ
trì tụng cũng là không trì tụng, dù không trì
tụng cũng là đang trì tụng, cho đến lúc niệm
niệm an nhiên không còn lay động ắt sẽ có sự
linh nghiệm.”

Tôi trước đây lấy hiệu là Học Hải, ngay
trong ngày hôm đó liền đổi hiệu là Liễu Phàm.
Đó là muốn nói việc học được thuyết _“tự lập
số mạng”_ này rồi nên không còn muốn rơi vào
khuôn khổ của những kẻ thế tục tầm thường.

Từ đó về sau, lúc nào tôi cũng chú tâm
tự phòng hộ suốt ngày, so với trước đây thật
hoàn toàn khác hẳn. Ngày trước tôi thường
buông thả phóng túng, còn bây giờ luôn nơm
nớp lo sợ [những việc xấu ác lầm lỗi], dù khi ở
trong nhà kín phòng tối [không ai nhìn thấy,
cũng không dám khởi lên những ý nghĩ xấu
ác, chỉ] sợ đắc tội với trời đất, quỷ thần. Gặp
những lúc bị người khác oán ghét, phỉ báng,
tôi vẫn có thể điềm nhiên chấp nhận.

Sang năm sau, bộ Lễ mở khoa thi Cử,^[Đây là khoa thi để chuẩn bị cho kỳ thi tuyển cử nhân.
Thí sinh buộc phải vượt qua được kỳ thi này mới được
tham dự kỳ thi Hương.
] tiên
sinh họ Khổng từng đoán trước khoa này tôi
sẽ đỗ hạng ba, hóa ra tôi lại đỗ hạng nhất.
Lời tiên đoán của Khổng tiên sinh không còn
đúng nữa, nên [khoa thi Hương] vào mùa thu
tôi lại đỗ tiếp Cử nhân.

Tuy nhiên, tôi làm việc thiện khi ấy vẫn
chưa được thuần thục, tự kiểm lại bản thân
còn nhiều lầm lỗi. Đôi khi thấy việc thiện thì
làm nhưng chưa thực sự quả quyết, mạnh
mẽ, hoặc có khi làm việc cứu giúp người khác
mà trong lòng mình thường tự nghi ngờ [kết
quả], hoặc có khi hành vi thì gắng theo việc
thiện nhưng lời nói lại có sai lầm, hoặc khi
tỉnh táo thì cố sức giữ gìn theo đạo đức, nhưng
lúc uống rượu vào rồi lại thường buông thả,
phóng túng. Mỗi ngày tôi đều xét điều lầm lỗi
trừ vào những việc thiện làm được, có hôm trừ
hết sạch chẳng còn gì cả. Vậy nên từ năm Kỷ
Tỵ^[Tức là năm 1569.] phát nguyện làm việc thiện mà phải đến
năm Kỷ Mão,^[Tức là năm 1579.] trải qua hơn 10 năm, mới hoàn
tất đủ số 3.000 điều thiện.

Khi ấy, tôi phát tâm cầu sinh con, lại cũng
nguyện làm đủ số 3.000 điều thiện. [Hai năm
sau là năm] Tân Tỵ^[Tức là năm 1581.] thì sinh được con trai
[đặt tên là] Thiên Khải.

Tôi làm được mỗi việc thiện đều ghi chép
lại. Vợ tôi không biết chữ nên mỗi khi làm được
một việc thiện thì dùng cán bút lông ngỗng
chấm mực đỏ in lên tờ lịch của ngày hôm đó
thành một chấm tròn, thường là những việc
thiện như bố thí thức ăn cho người nghèo,
hoặc mua vật sống phóng sinh... Những ngày
làm nhiều, có khi được đến hơn mười chấm
tròn như thế. Đến tháng 8 năm Quý Mùi^[Tức là năm 1583.] thì
đủ số 3.000 điều thiện. Ngày 13 tháng 9 năm
đó, tôi lại phát tâm cầu thi đỗ tiến sĩ, nguyện
làm 10.000 điều thiện.

Sang năm Bính Tuất^[Tức là năm 1586.] tôi thi đỗ tiến sĩ, được
bổ nhiệm làm Tri huyện Bảo Để. Tôi chuẩn bị
sẵn một quyển sổ trắng, đặt tên là sổ Trị tâm.
Sáng sớm khi lên công đường, tôi dặn người
nhà đem sổ ấy trao cho nha dịch để mang đặt
trên bàn làm việc của tôi. Mỗi một việc làm
trong ngày đều phân ra tốt xấu, ghi chép tỉ
mỉ vào sổ ấy, mỗi đêm lại bày hương án trước
sân, noi gương Triệu Duyệt Đạo ngày xưa cáo
trình tất cả lên Thượng đế.^[Triệu Duyệt Đạo, người Cù Châu thuộc tỉnh Chiết
Giang, tên thật là Triệu Biện, tên tự là Duyệt Đạo, tự
lấy hiệu là Tự Phi, sinh năm 1008, mất năm 1084.
Ông là một cư sĩ Phật giáo nổi danh, được ghi chép
trong Trung Quốc Phật học Nhân danh từ điển (trang
59) và Ngũ Đăng Hội Nguyên (quyển 16). Ông tánh
tình cương trực, sau khi đỗ tiến sĩ đã từng trải qua
nhiều chức quan ở các châu, quận. Đời Tống Nhân
Tông, ông giữ chức ngự sử, thường chính trực thẳng
thắn đến mức người ở kinh đô đều gọi ông là “Thiết
diện Ngự sử” (Quan Ngự sử mặt sắt). Tuổi già, ông
chuyên tâm tu niệm, tự sửa mình bằng cách mỗi đêm đều mang tất cả những việc đã làm trong ngày trình
cáo lên trời cao. Được 7 năm như thế rồi mới mất,
thọ 76 tuổi.]

Vợ tôi thấy những việc thiện ghi chép
không được nhiều thì chau mày nói rằng:
“Trước đây ông còn ở nhà, tôi có thể giúp sức
cùng ông làm việc thiện, nên con số 3.000
điều thiện mới được hoàn tất. Nay ông phát
nguyện làm đến 10.000 điều thiện mà trong
nha môn lại chẳng có nhiều việc thiện để làm,
vậy biết đến bao giờ mới có thể hoàn tất?”

Đêm đó, tôi nằm mộng bỗng gặp một vị
thần, liền đem việc khó làm đủ số điều thiện
mà trình bày với thần. Vị thần nói: “Chỉ riêng
một việc giảm thuế ruộng cho dân, xem như
một vạn điều thiện đã đủ số rồi.”

Nguyên là ruộng đất ở huyện Bảo Để
[trước đây] phải nộp thuế mỗi mẫu 2 phân 3
ly 7 hào,^[Đơn vị tiền tệ khi ấy lấy tiền làm đơn vị. Cứ mỗi tiền
có 10 phân, mỗi phân có 10 ly, mỗi ly có 10 hào.] [khi về nhậm chức] tôi có xem xét
lại, giảm xuống còn 1 phân 4 ly 6 hào. Quả
thật có việc đó, nhưng lòng tôi vẫn còn chút
nghi hoặc, [không cho rằng việc ấy lại có hiệu
quả lớn lao đến thế]. Vừa may khi ấy có Thiền
sư Huyễn Dư từ núi Ngũ Đài đến, tôi liền
em giấc mộng ấy kể lại với ngài rồi thưa hỏi
xem việc ấy có thể tin được chăng? Thiền sư
nói: “Nếu tâm thiện chân thành chí thiết, dù
làm một điều thiện cũng có thể bằng như vạn
điều thiện. Huống chi ông giảm thuế cho cả
một huyện, có cả vạn người dân được hưởng
phúc ấy.” Tôi liền dùng tiền lương bổng của
mình gửi nhờ Thiền sư về núi Ngũ Đài thay
mình thiết lễ trai tăng cúng dường một vạn vị
tăng để hồi hướng công đức.

Tiên sinh họ Khổng đoán rằng năm tôi 53
tuổi sẽ gặp tai nạn [rồi mất]. Tôi cũng chưa
từng cầu xin được sống lâu hơn, nhưng rồi
năm ấy trôi qua mà chẳng xảy việc gì cả. [Khi
viết chương sách này thì] tôi đã được 69 tuổi.

Kinh Thư nói: _“Lòng trời khó tin chắc,
mạng số không nhất định.”_ Lại nói: _“Chỉ
riêng mạng số là không nhất định.”_ Những
lời ấy đều không hư dối.

Tôi từ những việc đã qua mà hiểu được
rằng, mọi việc họa phúc đều do chính mình
chuốc lấy. Đó chính là lời dạy của các bậc
thánh hiền. Nếu cho rằng họa phúc đều do
trời định sẵn, đó chỉ là lời [mê muội] của
người thế tục [không biết tu tập] mà thôi.


Còn như khi chưa biết được số mạng thì
sao? Đang lúc thời vận được vinh hiển, hãy
thường tưởng như đang suy sụp, sa sút; đang
lúc thời vận thuận lợi, hãy thường tưởng như
đang gặp điều trái nghịch, trở ngại; đang lúc
được ấm no đầy đủ, hãy thường tưởng như
đang nghèo túng, đói thiếu; đang lúc được
người người yêu kính, hãy thường tưởng như
đang phải sợ sệt, lo lắng; đang lúc được quyền
cao chức trọng, hãy thường tưởng như đang ở
vào vị trí thấp hèn; đang lúc có được học vấn
cao xa, sâu rộng, hãy thường tưởng như mình
là người thiển cận, thô lậu.

Nghĩ xa thì thường lo việc nêu cao đức
hạnh của tổ tiên, nghĩ gần thì thường không
dám phơi bày lỗi lầm khiếm khuyết của cha
mẹ. Trên phải thường nghĩ việc báo đền ơn
tổ quốc, dưới phải luôn lo việc tạo phúc cho
gia đình; đối với bên ngoài phải luôn nghĩ
đến việc giúp người khi khẩn thiết, đối với tự
thân phải luôn ngăn ngừa những ý niệm tà
vạy của chính mình. Mỗi ngày đều [tự thẩm
xét để] biết lỗi mình thì mỗi ngày đều có sửa
lỗi; một ngày không tự biết lỗi mình thì ngày
ấy vẫn an nhiên tự cho mình là đúng. Một
ngày không có lỗi lầm nào được tu sửa thì
ngày ấy không hề có sự tiến bộ.

Người đời không ít kẻ thông minh tài trí,
nhưng sở dĩ không vun bồi phước đức cho sâu
dày, không phát triển nghiệp lành cho rộng
khắp, ấy chỉ vì sự quen theo nếp cũ, do dự rụt
rè, không đủ quyết tâm để nỗ lực thay đổi, tự
lập số mạng, nên cứ thế mà mê đắm trôi qua
hết một đời.

Thuyết “tự lập số mạng” mà Thiền sư Vân
Cốc đã truyền dạy quả thật hết sức sâu xa
tinh túy, quả thật là một nguyên lý hết sức
chân thật chính đáng. Ai có thể đọc kỹ những
lời dạy này rồi gắng sức làm theo ắt sẽ không
bỏ phí một đời trôi qua vô ích.
