# Tu sửa lỗi lầm {- #tu-sua-loi-lam}

 Các quan đại phu thời Xuân Thu
khi quan sát hành vi, lời nói của
một người thường dựa theo đó mà suy đoán
về những điều tốt xấu, họa phúc của người
đó, bao giờ cũng ứng nghiệm cả. Ngày nay,
chúng ta có thể xem lại những việc này trong
các sách Tả truyện, Quốc ngữ...

Nói chung, điềm báo những điều tốt lành
hay tai họa đều khởi lên từ trong tâm người,
rồi biểu hiện ra bên ngoài thành hành vi, lời
nói. Những người hết sức nhân hậu phóng
khoáng, tử tế với người khác thường được
phước lành, những kẻ hết sức khắt khe hẹp
hòi, bạc đãi người khác thường cận kề tai họa.
Người phàm mắt thịt bị nhiều che chướng
[không nhìn thấy được, do đó] cho rằng [vận
số] chưa xác định nên không thể suy lường
biết được.

Lòng người hết sức chân thành thì phù
hợp với đạo trời. Khi phước lành sắp đến,
quan sát việc làm thiện của người thì có thể
biết trước được. Khi tai họa sắp xảy ra, quan
sát việc làm xấu ác của người ắt cũng có thể
biết trước. Nay muốn được phước lành, tránh
xa tai họa, hãy khoan nói đến việc làm thiện
mà trước tiên là phải lo tu sửa lỗi lầm.

Bàn về việc tu sửa lỗi lầm, điều cốt yếu
trước tiên là phải khởi tâm biết xấu hổ. Hãy
nghĩ đến các bậc hiền thánh từ xưa, sao cũng
là thân người như ta nhưng lại có thể làm
bậc thầy của muôn thuở? Còn ta vì sao suốt
một đời kém cỏi, vô dụng như gạch vụn, ngói
bể? Ấy chỉ vì ta mê đắm trong tình đời, lén
lút làm những điều trái nghịch đạo nghĩa,
lại cho rằng người khác không ai biết nên
thản nhiên cao ngạo, không chút hổ thẹn,
ngày sau sa đọa vào loài cầm thú mà không
hề tự biết. Việc đáng xấu hổ trong đời này
thật không gì lớn hơn thế nữa. Mạnh tử nói:
_“Biết xấu hổ là [đức tính] quan trọng của con
người. Giữ được tâm tính ấy là thánh hiền,
đánh mất đi thì chẳng khác gì cầm thú.”_ Cho
nên, khởi tâm biết xấu hổ là nền tảng cốt yếu
nhất trong việc tu sửa lỗi lầm.

Điều [quan trọng] tiếp theo là phải biết
khởi tâm sợ sệt [không dám làm điều sai trái].
Trời đất từ trên soi thấu, quỷ thần không dễ
dối lừa. Nay ta làm điều sai trái, tuy là ở nơi
ẩn khuất [không ai thấy biết], nhưng trời đất
quỷ thần thật soi xét thấy rõ. Nếu là tội nặng,
ắt sẽ giáng xuống trăm tai ngàn họa; nếu là
tội nhẹ, ắt sẽ hao tổn phước đức hiện có; như
thế làm sao có thể không lo sợ?

Không chỉ ở nơi vắng vẻ khuất tất là như
thế, mà giữa những chốn đông người qua lại
cũng như thế, cho dù ta cố che giấu thật kín
đáo, biện bạch thật khéo léo, nhưng những
điều giấu trong gan ruột rồi cũng sẽ sớm lộ ra,
rốt cuộc cũng không thể tự dối lòng mình. Đến
khi bị người khác phát hiện biết rõ [việc xấu
mình làm, thì nhân cách tự thân] thật chẳng
đáng một xu! Như vậy có thể không sợ được
sao?

Hơn nữa, chỉ cần chúng ta còn một hơi thở
thì dù tội lỗi lớn đến đâu cũng có thể hối cải.
Xưa có người suốt đời làm việc xấu ác, đến
khi sắp chết mới tỉnh ngộ hối lỗi, phát khởi
một niệm lành, liền được kết quả tốt đẹp. Cho
nên nói rằng, khởi một niệm lành hết sức
mạnh mẽ có thể đối trị được những điều xấu
ác trong cả trăm năm. Cũng giống như hang
sâu tăm tối ngàn năm, chỉ một ngọn đèn vừa
chiếu sáng thì bóng tối ngàn năm lập tức bị
phá trừ. Vì thế, những việc lỗi lầm bất luận
là phạm vào đã lâu hay chỉ mới gần đây, phải
lấy việc biết tu sửa là điều đáng quý nhất.

Cuộc đời vô thường, thân người hết sức
mong manh dễ mất, chỉ một hơi thở dừng
lại không tiếp nối thì dù muốn hối cải tu sửa
cũng không còn kịp nữa. Khi ấy thì trên chốn
dương gian phải cam chịu tiếng xấu ngàn
năm, cho dù con thảo cháu hiền cũng không
thể thay ta rửa sạch; lại dưới cõi u minh ắt
phải trầm luân ngàn kiếp trong địa ngục cam
chịu nghiệp báo, cho dù là các vị thánh hiền
hay Phật, Bồ Tát cũng không thể dẫn dắt cứu
ta ra khỏi. Ôi, như thế có thể nào không sợ
được sao?

Điều [quan trọng] thứ ba là phải phát tâm
[tu sửa] thật dũng mãnh. Người đời đa phần
không thể tu sửa lỗi lầm là vì cứ quen theo nếp
cũ mà sa đọa, chúng ta cần phải phấn chấn
mạnh mẽ vươn lên, không được phân vân trì
trệ, không được chậm trễ dùng dằng. Đối với
lỗi nhỏ nhặt phải xem như bị gai đâm vào thịt,
cần nhanh chóng lấy ra. Đối với lỗi nặng nề
nghiêm trọng, phải xem như bị rắn độc cắn
vào ngón tay, lập tức chặt bỏ không chút chần
chừ. Đó là nói đến lợi ích của [sự phát tâm
dũng mãnh, nhanh chóng như] sấm chớp, như
gió mạnh.

Phát khởi đầy đủ 3 tâm niệm như trên,
[biết hổ thẹn, biết sợ sệt lỗi lầm và quyết tâm
tu sửa thật dũng mãnh] thì mỗi khi mắc phải
lỗi lầm liền sửa đổi được ngay. Ví như lớp
băng mùa xuân gặp ánh mặt trời, lo gì không
tan chảy?

Tuy nhiên, lỗi lầm xấu ác của con người
có thể theo nơi sự việc biểu hiện mà tu sửa,
cũng có thể dựa trên sự suy xét đạo lý mà tu
sửa, lại cũng có thể ngay từ trong tâm ý mà
tu sửa. Mỗi phương cách tu sửa như vậy đòi
hỏi công phu khác nhau, mà hiệu quả cũng
khác nhau.

Chẳng hạn như ngày trước thường giết
hại sinh mạng, nay giữ giới không giết hại;
hoặc như ngày trước thường nóng giận, nay
cố ngăn giữ không còn nóng giận. Những sự
tu sửa như thế là theo nơi sự việc biểu hiện
mà tu sửa. Tu sửa theo cách như vậy là cố sức
kiềm chế [sự việc đã biểu lộ ra] bên ngoài,
nên thật hết sức khó khăn, nhưng cội gốc của
những lỗi lầm ấy rốt cuộc vẫn còn nguyên
đó, trừ bỏ nơi này lại nảy sinh nơi khác, thật
không phải phương cách rốt ráo để tu sửa
triệt để mọi lỗi lầm.

Người khéo léo hơn trong việc tu sửa lỗi
lầm thì khi sự việc còn chưa biểu lộ ra bên
ngoài đã sớm suy xét đạo lý của sự việc ấy.
Chẳng hạn như đối với việc giết hại sinh
mạng, liền suy xét theo đạo lý rằng: “Trời đất
luôn có đức hiếu sinh, muôn loài đều tham
sống sợ chết, nay ta giết hại loài vật để nuôi
dưỡng thân mình, làm sao có thể tự thấy an
ổn trong lòng? Hơn nữa, con vật bị giết kia,
đã bị đâm chém cắt xẻo, rồi lại bị cho vào nồi
nước sôi, chảo dầu nóng, đau đớn thống khổ
thấu tận xương tủy, ta lại dùng thân xác nó
để nuôi dưỡng mình, dẫu có bày ra thành
trăm món ngon lạ, ăn qua khỏi miệng cũng
đều tiêu mất. Trong khi đó, chỉ cần canh rau
đơn sơ cũng đủ no bụng, vì sao phải giết hại
sinh mạng của muôn loài, làm tổn hại đến
phước đức của mình?”

Lại suy xét đến việc hết thảy muôn loài có
máu thịt, khí chất, cũng đều có linh tính, tri
giác. Đã có linh tính, tri giác thì đối với [loài
người] chúng ta cũng là cùng một bản thể. Nay
tự thân ta đã không thể tu tập thành bậc chí
tôn chí đức để muôn loài phải tôn kính, gần
gũi nương cậy ta, lẽ nào lại còn xuống tay giết
hại sinh mạng của chúng, khiến chúng phải
đem lòng oán hận, căm thù ta không sao nói
hết?

Suy xét được thấu đáo những điều như thế
thì khi nhìn thấy món ăn [do giết hại mà có]
ắt phải hết sức đau lòng, không thể nào nuốt
trôi qua khỏi cổ.

Hoặc như trước đây vốn thường nóng giận,
liền suy xét rằng: “Đối với người có chỗ [cư
xử kém cỏi] chẳng bằng ta, xét về tình thì
nên khởi lòng thương xót họ mới đúng; đối
với người làm việc trái lý lẽ [xúc phạm ta] thì
đó là sai trái của họ, nào có liên quan gì đến
ta?” Nghĩ như thế thì thấy thật không có gì
để giận dữ cả.

Lại suy xét rằng, trong thiên hạ chẳng có
bậc hào kiệt nào lại tự mãn luôn cho mình
là đúng, cũng không có học thuyết nào dạy
ta oán ghét người khác. Công hạnh có điều
chưa đạt được đều là do phước đức tự thân
ta chưa tu tập đúng mức, chưa đủ cảm hóa
người khác, ta cần phải lấy những điều đó để
tự phản tỉnh, suy xét về bản thân mình. Như
vậy thì khi có người đến phỉ báng, làm nhục,
liền xem đó như sự cọ xát, rèn luyện [giúp
đá thô] thành ngọc quý, như thế ắt phải vui
mừng đón nhận, làm sao có thể nổi giận?

Hơn thế nữa, nếu ta bị phỉ báng mà không
nổi giận, thì những lời xúc phạm ấy dù có
nhiều đến đâu cũng chỉ như kẻ đốt lửa giữa
khoảng không, rốt cuộc cũng phải tự lịm tắt.
Bằng như nghe lời phỉ báng mà nổi giận thì
cho dù hết lòng khéo léo biện bạch cũng chẳng
khác nào con tằm mùa xuân nhả tơ làm kén,
ngày càng tự trói chặt lấy chính mình. Như
vậy, sự nóng giận chẳng những là vô ích mà
còn gây hại nữa.

Đối với với hết thảy những lỗi lầm xấu ác
khác cũng đều dựa theo đạo lý mà suy xét
như thế. Nếu sự suy xét đạo lý đã được rõ
ràng sáng tỏ thì mọi lỗi lầm xấu ác đều sẽ tự
chấm dứt.

Thế nào là tu sửa lỗi lầm ngay từ trong
tâm? [Đó là tự xét rằng], lỗi lầm xấu ác của
con người có vô số nguyên nhân, nhưng hết
thảy đều do tâm tạo tác. Nếu trong tâm mình
an nhiên bất động thì lỗi lầm dựa vào đâu mà
sinh khởi? Người tu học [phương pháp sửa lỗi
này] đối với những lỗi lầm xấu ác như háo
sắc, tham danh, tham tiền của, dễ nóng giận
v.v... không cần thiết phải truy đuổi tìm kiếm
đối trị từng loại, chỉ cần một lòng chuyên chú
làm thiện, lúc nào cũng duy trì ý niệm chân
chánh, thì bao nhiêu ý niệm tà vạy xấu ác sẽ
tự nhiên không thể khởi lên làm ô nhiễm. Ví
như khi mặt trời rực sáng giữa không trung,
các loài yêu ma quỷ quái thảy đều trốn mất.
Đây là [phương pháp sửa lỗi] chân truyền
tinh tế nhất. Mọi lỗi lầm đều do tâm tạo tác,
nên cũng do nơi tâm mà sửa đổi. Ví như việc
đốn trừ loài cây độc, phải trực tiếp chặt phá
ngay vào gốc rễ, đâu cần phải đốn tỉa từng
cành nhánh, ngắt bỏ từng chiếc lá?

Nói chung thì phương pháp đối trị [lỗi lầm]
ngay từ trong tâm là vượt trội và [hiệu quả]
hơn hết. Đang khi tu tập giữ tâm thanh tịnh,
nếu trong tâm vừa khởi động niệm [xấu ác]
liền tức thời rõ biết; rõ biết rồi thì niệm [xấu
ác đó] liền tự nhiên không còn nữa.

Bằng như chưa đủ sức để tu tập theo
phương pháp trị tâm, thì nên dùng phương
pháp suy xét rõ ràng theo đạo lý để trừ bỏ lỗi
lầm.

Nếu vẫn chưa đủ sức dùng phương pháp
suy lý, thì nên dùng phương pháp đối trị theo
sự việc [sai trái] đã biểu hiện.

Nếu như sử dụng phương pháp trị tâm
cao nhất, đồng thời kèm theo những phương
pháp còn lại, như vậy cũng chẳng có gì sai
lầm. Nhưng nếu chỉ biết sử dụng những
phương pháp kém hiệu quả mà không biết
đến phương pháp vượt trội hơn thì thật là
khờ dại.

Cho nên, khi phát nguyện sửa đổi lỗi lầm
xấu ác, thì giữa nơi sáng rõ nên cầu được
bạn tốt nhắc nhở, ở chỗ u tối khuất lấp nên
nguyện có quỷ thần soi xét chứng minh. Hết
lòng sám hối [những tội lỗi đã qua], ngày
đêm không chút giải đãi buông lung, trải qua
một tuần, hai tuần, cho đến một tháng, hai
tháng, ba tháng... ắt phải có hiệu quả ứng
nghiệm. Chẳng hạn như cảm thấy tinh thần
điềm nhiên, thư thái khoáng đạt; hoặc cảm
thấy như trí tuệ khai mở, hốt nhiên sáng
suốt; hoặc có những lúc rơi vào cảnh rối ren
phiền nhiễu nhưng cảm xúc, suy nghĩ đều
suốt thông không vướng mắc; hoặc có những
lúc gặp kẻ oán thù nhưng có thể bình tâm đổi
giận làm vui; hoặc mơ thấy nôn mửa ra vật
đen tối; hoặc mộng thấy các bậc hiền thánh
ngày trước hiện đến dắt dẫn ân cần; hoặc mơ
thấy mình đi lại nhẹ nhàng trên hư không,
hoặc mộng thấy những thứ như cờ phướn,
lọng quý, đủ mọi cảnh tượng thù thắng tốt
đẹp... Hết thảy những điều như thế đều là
biểu hiện của việc đã dứt trừ được lỗi lầm
xấu ác. Tuy nhiên, không được bám chấp vào
những thành tựu như thế mà vội khởi tâm
cao ngạo tự mãn, vì như thế sẽ ngăn trở ta
không thể tiến bộ thêm nữa.

Xưa có người tên Cừ Bá Ngọc, khoảng
năm 20 tuổi đã thấy rõ được những lỗi lầm
xấu ác trước đây của mình và dứt trừ sửa đổi
được hết thảy. Sang đến năm 21 tuổi mới biết
những sự cải hối trước đây của mình thật ra
vẫn chưa dứt hết [được lỗi lầm]. Sang năm 22
tuổi thì ông nhìn lại năm 21 tuổi, [quan sát
những việc đã qua] như trong giấc mộng, [lại
tiếp tục sửa lỗi]. Cứ như thế năm này sang
năm khác, ông vẫn kiên trì tuần tự sửa lỗi.
Cho đến năm 50 tuổi vẫn còn [nhìn lại] thấy
được lỗi lầm của năm 49 tuổi.

Việc học sửa lỗi của người xưa là như thế.
Chúng ta đều là những kẻ phàm tục tầm
thường, những điều lỗi lầm xấu ác tích tụ
dẫy đầy không kể xiết, thế mà khi nhìn lại
những việc đã qua lại thường chẳng thấy
được lỗi lầm chi cả! Ấy là bởi tâm mê muội
nên mắt bị che mờ.

Tuy nhiên, con người khi lỗi lầm xấu ác
quá sâu nặng cũng có những biểu hiện có thể
thấy được. Chẳng hạn như tinh thần u ám,
bế tắc, nói trước quên sau, hoặc không duyên
cớ gì nhưng trong tâm vẫn thường phiền
não, bực dọc; hoặc đối diện với người hiền
lương quân tử thì cảm thấy hổ thẹn ngượng
ngùng; hoặc được nghe những lời bàn luận
chân chánh nhưng lại không vui thích; hoặc
thường bị rơi vào cảnh làm ơn mắc oán; hoặc
đêm nằm mộng thấy những chuyện điên đảo
trái nghịch... Nếu nặng nề quá có thể sinh ra
nói năng lộn xộn, tâm thần bất định... Hết
thảy những điều như vậy đều là biểu hiện
của việc làm xấu ác. Nếu thấy có một trong
những biểu hiện như thế thì phải lập tức phát
tâm mạnh mẽ phấn chấn, quyết lòng dứt bỏ
lỗi cũ, dựng xây đời mới.

Mong sao người đọc [hiểu đúng được những
điều như trên để] không tự dối mình.
