# Tích chứa điều lành {- #tich-chua-dieu-lanh}

Kinh Dịch nói: _“Nhà nào tích chứa
điều lành ắt có thừa niềm vui.”_
Thuở xưa, họ Nhan mang con gái gả cho Thúc
Lương Hột vì xét thấy tổ tiên nhiều đời của
ông này từng tạo nhiều phước đức, do đó tin
chắc rằng con cháu về sau ắt phải được hưng
thịnh, tốt đẹp.^[Thúc Lương Hột về sau sinh ra một bậc thánh nhân,
chính là đức Khổng tử.] Đức Khổng tử khi ngợi khen
vua Thuấn là bậc đại hiếu có nói rằng: _“Tông
miếu tổ tiên được thờ kính, con cháu nhiều
đời gìn giữ phước lành.”_ Những lời như thế
đều là sự luận giải rốt ráo, rõ ràng. Nay ta
lại thử đem những chuyện có thật đã qua để
chứng minh cho lập luận này.

Quan Thiếu sư họ Dương, tên Vinh, quê
ở huyện Kiến Ninh,^[Huyện này thuộc tỉnh Phúc Kiến. Tiên sinh An Sĩ
đã có kể lại câu chuyện này trong phần Giảng rộng
nghĩa lý bài văn Âm chất, quyển Hạ, phần giảng
rộng câu “Sông rộng giúp thuyền bè đưa người qua
lại”. Ở đây chúng tôi dịch sát theo văn của Viên Liễu
Phàm.
] tổ tiên nhiều đời làm
nghề chèo thuyền [đưa người sang sông] để
sinh sống. Gặp lúc trời mưa lâu, nước sông
suối dâng cao, dòng chảy rất xiết, cuốn trôi
cả những vùng dân cư, người chết đuối cứ
theo dòng sông mà trôi xuống. Những thuyền
khác đều tranh nhau vớt lấy tài sản quý giá
trôi trên sông, chỉ riêng ông cố và ông nội của
Thiếu sư, hai người đều hết sức lo việc cứu
người, hoàn toàn không vớt lấy một chút tài
vật nào. Người trong làng đều cười chê họ là
ngu dại.

Đến khi cha của Thiếu sư ra đời, gia đình
dần dần khá giả lên. Bỗng có vị thần hóa hình
thành một đạo nhân đến bảo người nhà rằng:
“Tổ phụ các người có âm đức lớn, con cháu sẽ
được giàu có vinh hiển, nên cải táng [mộ tổ
phụ] vào chỗ đất này...” Nói rồi chỉ cho một
chỗ đất. Người nhà y theo chỉ dẫn của đạo
nhân mà cải táng. Chỗ ấy sau này các thầy
địa lý đều gọi là gò bạch thố.

Về sau sinh ra Thiếu sư, còn nhỏ tuổi^[Nguyên tác dùng “nhược quán” (弱冠) tức là lễ đội
mũ. Ngày xưa làm lễ này để đánh dấu lúc người con
trai thực sự trưởng thành, thường là vào năm 20 tuổi.
Tuy nhiên, theo ước lệ thì từ này được dùng chỉ chung
những người trẻ tuổi, vừa mới trưởng thành.] đã
thi cử đỗ đạt, làm quan tước vị lên đến Tam
công. Ông cố và ông nội của Thiếu sư đều được
triều đình truy tặng quan tước như vậy. Con
cháu về sau đều được hưng thịnh, tốt đẹp,
cho đến nay^[Tức là vào thời của Viên Liễu Phàm.] vẫn còn nhiều người hiền đức.

* * *

Dương Tự Trừng người huyện Ngân,^[Huyện Ngân ngày nay là huyện Ninh Ba, thuộc tỉnh
Chiết Giang. Tiên sinh An Sĩ có kể chuyện ông này
trong phần Giảng rộng nghĩa lý bài văn Âm chất,
quyển Hạ, phần giảng rộng câu “Hết thảy việc ác
quyết không làm, hết thảy việc lành xin vâng theo”,
chuyện “Chịu đói nuôi tù”, nhưng chép tên là Dương
Sĩ Trừng (楊士懲) và có một vài chi tiết nhỏ khác
biệt. Ở đây chúng tôi dịch sát theo văn của Viên Liễu
Phàm.] ban
đầu vốn chỉ là một viên thư lại trong nha
huyện, luôn giữ lòng nhân hậu, thi hành pháp
luật một cách công bình. Quan huyện khi ấy
là người nghiêm khắc, một hôm tùy tiện dùng
roi đánh một người tù đến nỗi máu chảy đầy
sân mà vẫn chưa hết cơn giận. Họ Dương quỳ
xuống xin tha. Quan huyện nói: “Người này
vi phạm pháp luật, làm trái đạo lý, ta làm
sao có thể không tức giận?” Tự Trừng khấu
đầu thưa rằng: “[Tăng tử có nói:] ‘Bề trên lỗi
đạo, dân chúng phóng túng buông thả đã lâu,
như hiểu được tình cảnh đó thì [khi xét xử tội
trạng] nên thương xót họ, chớ lấy [việc trừng
phạt được tội ác] làm vui.’^[Ở đây họ Dương dẫn lời Tăng tử trong sách Luận
ngữ. Khi Dương Phu được mời ra làm quan phụ trách
hình pháp, có đến xin Tăng tử chỉ dạy. Ông nói: “
上失其道，民散久矣！如得其情，則哀矜而勿喜。-
Thượng thất kỳ đạo, dân tán cửu hỹ. Như đắc kỳ tình,
tắc ai căng nhi vật hỷ.” (Bề trên lỗi đạo, dân chúng
phóng túng buông thả đã lâu, như hiểu được tình
cảnh đó thì [khi xét xử tội trạng] nên thương xót họ,
chớ lấy [việc trừng phạt được tội ác] làm vui.) Xem
sách Luận ngữ, chương thứ 19 - Tử Trương, tiết thứ
19.] [Theo như lời ấy
thì] vui còn không được, huống chi lại nổi
giận?” Quan huyện nghe lời ấy rồi liền thôi
không giận nữa.

Nhà Tự Trừng rất nghèo, nhưng có ai
mang quà biếu đến đều tuyệt đối không
nhận. Gặp lúc thiếu lương thực, tù nhân phải
chịu đói, ông thường tìm đủ mọi cách để có
cho họ ăn. Ngày kia, có thêm một số tù nhân
mới được giải đến đang đợi cho ăn, gặp lúc
nhà ông đã gần hết gạo, nếu mang cấp cho tù
nhân thì cả nhà phải chịu đói, nếu giữ gạo lại
ăn thì những người tù kia thật đáng thương.
Ông liền đem việc ấy bàn với vợ. Vợ ông hỏi:
“Những người tù ấy từ đâu chuyển đến?” Ông
đáp: “Từ Hàng Châu đến, dọc đường đã phải
chịu đói rất lâu, thấy rõ sắc mặt xanh lè!”
Nhân đó, [vợ chồng] ông liền lấy hết số gạo
còn lại trong nhà, nấu cháo mang đến cho tù
nhân ăn.

Về sau, ông sinh được 2 người con trai. Con
trưởng là Dương Thủ Trần, con thứ là Dương
Thủ Chỉ, cả 2 đều làm quan Lại Bộ Thị lang
ở 2 vùng Nam (kinh) và Bắc (kinh).^[Tiên sinh An Sĩ chỉ đề cập đến một người con của
ông này là Dương Thủ Trần, làm quan đến chức Hàn
Lâm Học sĩ.] Lại có 2
người cháu nội, cháu lớn làm quan đến chức
Hình Bộ Thị lang, cháu nhỏ làm quan Liêm
Hiến^[Liêm Hiến: chức quan này về sau gọi là Án Sát, phụ
trách về hình sự.] ở tỉnh Tứ Xuyên, đều là những vị quan
có danh tiếng. Ngày nay,^[Tức vào thời tiên sinh Viên Liễu Phàm.] các ông Sở Đình,
Đức Chính đều là con cháu của Dương Tự Trừng.

* * *

Trong khoảng niên hiệu Chính Thống,^[Niên hiệu Chính Thống là vào đời vua Minh Anh Tông, kéo dài từ năm 1436 đến năm 1449.]
Đặng Mậu Thất cầm đầu nổi loạn ở Phúc
Kiến, những kẻ có học và dân thường cùng
theo hưởng ứng rất đông. Triều đình cử quan
Đô hiến là Trương Giai từ huyện Ngân kéo
quân về phía nam để chinh phạt. Trương
Đô hiến dùng mưu bắt được giặc loạn, sau
đó liền cử viên Đô sự họ Tạ thuộc Bố Chánh
ty [của tỉnh Phúc Kiến] đi truy lùng bắt giết
những kẻ theo giặc loạn. Tạ Đô sự cố sức điều
tra được danh sách những người đã theo giặc.
Sau đó, đối với những gia đình nào không có
tên trong danh sách liền kín đáo sai người
đến trao cho một lá cờ nhỏ bằng vải trắng,
dặn họ vào ngày quân binh truy quét thì cắm
lá cờ ấy trước cửa. Tạ Đô sự lại nghiêm cấm
quân lính không được giết người bừa bãi, nhờ
vậy mà cứu sống được đến hàng vạn người
[không phải chết oan].

Về sau, con trai của Tạ Đô sự là Tạ Thiên
thi đỗ Trạng nguyên, làm quan đến chức Tể
tướng. Cháu nội là Tạ Phi cũng đỗ Thám hoa.


* * *

Ở huyện Bồ Điền [thuộc tỉnh Phúc Kiến]
có nhà họ Lâm, đời trước có một lão bà ưa
thích làm điều thiện, thường làm bánh bột
gạo rồi đem bố thí cho người, ai đến xin cũng
cho, không chút phiền hà. Có một vị tiên hóa
hình làm đạo nhân, sáng nào cũng đến xin
đến 6, 7 cái bánh. Lão bà ngày nào cũng đưa
cho, trải qua 3 năm đều đặn như vậy. Vị tiên
thấy được tấm lòng chân thành của bà rồi,
liền nói: “Ta ăn bánh của bà đã 3 năm, biết
làm sao đền đáp? Sau nhà bà có một chỗ đất,
[khi nào bà mất đi, dặn trước người nhà hãy]
chôn cất bà nơi ấy, con cháu về sau sẽ được
hưởng quan tước nhiều như số hạt mè trong
một thăng mè.”

Người con trai theo lời mẹ dặn, chôn cất
lão bà nơi chỗ đất ấy. Ngay đời sau đó đã có 9
người đỗ đạt. Trải qua nhiều đời sau nữa thì
những người quyền quý quan tước trong họ ấy
rất nhiều. Tỉnh Phúc Kiến có lưu truyền câu
tục ngữ rằng: “Không có họ Lâm thì không
lập được bảng vàng” [ý nói không một khoa
thi nào lại không có người họ Lâm đỗ đạt].

* * *

Cha của quan Thái sử Phùng Trác Am^[Tiên sinh An Sĩ có kể lại câu chuyện này phần Giảng
rộng nghĩa lý bài văn Âm chất, quyển Thượng, phần
giảng rộng câu “Chu cấp cơm ăn áo mặc cho người
lỡ đường đói rét”, với một số chi tiết hơi khác biệt. Ở
đây chúng tôi dịch sát theo văn của Viên Liễu Phàm.
] khi
còn học ở trường huyện, vào một ngày mùa
đông cực kỳ rét buốt, dậy sớm đến trường học,
giữa đường bỗng nhìn thấy một người bị ngã
nằm trong đống tuyết, đến sờ vào thì thấy
đã bị tê cứng đến nửa người rồi. Ông liền cởi
chiếc áo ấm đang mặc ra đắp cho người ấy, rồi
đưa về nhà cứu sống.

Sau đó, ông mộng thấy một vị thần bảo
rằng: “Ông cứu được một mạng người, có
tâm chí thành, nay ta sai Hàn Kỳ^[Hàn Kỳ (1008-1075) vốn là một vị Tể tướng có tài
văn võ song toàn vào đời Tống.
] đến làm
con ông.” [Nhân đó nên] đến khi sinh con
trai liền đặt tên là Phùng Kỳ, [sau mới lấy
hiệu là Trác Am].

* * *

Quan Thượng thư họ Ưng người Đài Châu
[thuộc tỉnh Chiết Giang], thuở còn thanh niên
học tập trong vùng núi, ban đêm có bọn ma
quỷ tụ tập kêu rú, thường khiến mọi người
kinh sợ, nhưng riêng ông không chút sợ sệt.

Một đêm nọ, ông nghe tiếng quỷ nói: “Có
một phụ nữ kia vì chồng đi xa đã lâu không
về, cha mẹ chồng [nghĩ là con mình đã chết
nên] ép cô ấy phải lấy chồng khác. [Cô ấy
không chịu nên] đêm mai sẽ thắt cổ tự tử ở
nơi ấy. Vậy là ta có người thế thân rồi.”

Họ Ưng nghe biết được tên người phụ nữ
trong câu chuyện, liền ngầm bán ruộng nhà
được 4 lượng bạc, rồi viết một bức thư giả làm
thư của người chồng gửi về nhà, kèm theo cả
4 lượng bạc. Cha mẹ chồng của người phụ nữ
kia được thư, xem chữ viết không phải của con
mình nên nghi ngờ, nhưng rồi lại nghĩ: “Thư
có thể giả, nhưng tiền làm sao giả được?” Vì
thế, họ cho rằng con mình vẫn bình an không
xảy ra chuyện gì. Người phụ nữ kia nhờ vậy
không [bị ép] lấy chồng khác.

Về sau, người chồng quay về, vợ chồng lại
được đoàn tụ như xưa. Một đêm, họ Ưng lại
nghe quỷ nói với nhau: “Ta đã sắp có người thế
thân, chỉ do gã tú tài này phá hỏng chuyện
của ta.” Có con quỷ gần đó hỏi: “Sao mày
không hại nó?” Quỷ kia đáp rằng: “Thượng
đế thấy người này tâm địa tốt lành nên đã
truyền lệnh ghi âm đức cho ông ta sau này
sẽ làm quan Thượng thư, tao làm sao có thể
hại được?”

Họ Ưng nghe như vậy càng thêm nỗ lực,
việc thiện ngày càng làm được nhiều hơn,
phước đức càng thêm sâu dày. Gặp năm mất
mùa đói kém, ông liền mang gạo của nhà ra
cứu giúp cho người đói; gặp người thân thích
có việc nguy cấp, ông liền ân cần giúp đỡ họ
vượt qua; gặp những hoàn cảnh trái nghịch,
ông thường quay lại tự xét lỗi mình rồi vui vẻ
chấp nhận. Con cháu của ông đỗ đạt thành
danh, tính đến nay^[Tức là vào thời đại của tiên sinh Viên Liễu Phàm.] số lượng rất nhiều.

* * *

Huyện Thường Thục [thuộc tỉnh Giang
Tô] có người tên Từ Thức, hiệu Phượng Trúc.
Cha ông vốn là người giàu có. Gặp một năm
mất mùa đói kém, cha ông là người trước tiên
trong toàn huyện đề xướng việc hủy bỏ không
thu tô [của nông dân], sau đó lại mang lúa
gạo trong nhà ra phân phát cứu giúp người
đói thiếu. Đến đêm nghe tiếng quỷ thần nơi
cửa trước hô to rằng: “Ngàn vạn lần quyết
không lừa dối, tú tài nhà họ Từ sẽ đỗ cử
nhân.” Nhiều đêm liên tiếp đều nghe tiếng
hô to như vậy. Năm ấy, Phượng Trúc dự kỳ
thi Hương quả nhiên đỗ cử nhân. Cha ông
nhân đó càng nỗ lực làm thiện, ngày càng
nhiều hơn, không chút biếng trễ. Những việc
như tu sửa cầu đường, cúng dường trai tăng,
cứu giúp người nghèo đói... cho đến hết thảy
những việc mang lại lợi ích [cho người khác]
ông đều cố hết sức làm. Về sau lại nghe tiếng
quỷ thần hô to nơi cửa trước rằng: “Ngàn vạn
lần quyết không lừa dối, cử nhân nhà họ Từ
sẽ làm quan đến chức Đô Đường.”^[ Danh xưng Đô Đường vào đời nhà Đường chỉ chung 6
vị quan Thượng thư, vì nơi làm việc của họ đặt chung
trong một tòa nhà gọi là Đô Đường. Phía đông gồm
bộ Lại, bộ Hộ, bộ Lễ; phía tây gồm bộ Hình, bộ Binh,
bộ Công. Triều Đường, triều Tống, triều Kim đều gọi
nơi làm việc của vị quan đầu tỉnh là Đô Đường, nên
quan đầu tỉnh cũng gọi là Đô Đường. Triều Minh
dùng danh xưng Đô Đường để gọi các quan đứng
đầu Đô Sát viện, như Đô Ngự sử, Phó Đô Ngự sử...
Các quan tuần phủ được phong các quan hàm như
trên cũng đều được gọi là Đô Đường. Đây là trường
hợp của của Từ Phượng Trúc, vì ông được phong làm
Tuần phủ Lưỡng Chiết.] Về sau,
Phượng Trúc [quả nhiên] làm quan đến chức
Tuần phủ Lưỡng Chiết.^[Lưỡng Chiết: danh xưng có từ đời Bắc Tống, bao gồm
Chiết Đông và Chiết Tây, về sau đều hợp lại thuộc
địa phận tỉnh Chiết Giang.]

* * *

Có viên Chủ sự bộ Hình tên Đồ Khang
Hy là người quê ở phủ Gia Hưng [thuộc tỉnh
Chiết Giang]. Một đêm nọ, ông vào trong
ngục, thận trọng tra hỏi tỉ mỉ trường hợp của
từng người tù, qua đó phát hiện được một số
người vô tội. Ông không lấy đó làm công lao
của riêng mình, liền bí mật viết hết lời khai
của các tù nhân thành văn bản trình lên quan
Thượng thư bộ Hình. Sáng sớm hôm sau khi
xét xử tội nhân, quan Thượng thư dựa theo
những lời ông đã báo lên mà tra hỏi, hết thảy
tù nhân đều khâm phục nhận chịu, nhờ đó
làm rõ và phóng thích được hơn mười người
bị oan. Bấy giờ, [qua sự việc ấy,] dân chúng
ở kinh đô đều ca tụng quan Thượng thư là
người sáng suốt.

Đồ Khang Hy lại thưa với quan Thượng
thư rằng: “Ngay ở chốn kinh thành mà còn
có nhiều người dân bị oan ức, dân chúng bốn
phương số nhiều đến hàng triệu người, lẽ nào
lại không có những kẻ bị oan? Vì thế, cứ 5
năm một lần triều đình nên cử một vị quan
Giảm hình [về các địa phương] tra xét sự thật
[các vụ án] để phán xử lại cho công bằng.”
Quan Thượng thư trình tấu đề nghị ấy lên
triều đình, được chuẩn y. Bấy giờ, Đồ Khang
Hy cũng được đề cử làm một trong số các
quan Giảm hình.

Đêm nọ, Đồ Khang Hy mộng thấy một vị
thần bảo rằng: “Mạng số của ông vốn không
có con, nay ông đề nghị việc giảm hình rất hợp
lòng trời, Ngọc Đế ban cho ông 3 người con,
về sau đều sẽ được áo tía đai vàng.”^[Áo tía đai vàng: có nghĩa là được đỗ đạt làm quan
hiển hách. Áo tía (tử y) và đai vàng (kim yêu) đều là
những thứ do triều đình ban tặng cho người có công
trạng.] Đêm ấy,
vợ ông có thai rồi sinh ra con trai là Đồ Ứng
Huân. Sau lại sinh được Đồ Ứng Khôn, Đồ
Ứng Tuấn. Cả ba người con ấy sau đều được
quan tước hiển vinh.

* * *

Phủ Gia Hưng [thuộc tỉnh Chiết Giang] có
người tên Bao Bằng, tự là Tín Chi. Cha ông làm
quan Thái thú Trì Dương,^[Trì Dương: nay là huyện Kinh Dương và một phần của
huyện Tam Nguyên, đều thuộc quận Hàm Dương,
tỉnh Thiểm Tây.] sinh được 7 người
con. Bao Bằng là con út, làm rể nhà họ Viên
ở huyện Bình Hồ [cũng thuộc phủ Gia Hưng].
Ông Bao Bằng với cha tôi^[Tức tiên sinh Viên Liễu Phàm tự kể lại chuyện này.] có giao tình hết sức
thân mật. Ông học rộng tài cao nhưng đi thi
nhiều lần không đỗ, [liền quay sang] chú tâm
vào Phật học và Lão học.^[Nguyên bản dùng nhị thị (二氏) để chỉ đạo Phật và
đạo Lão.
] Một hôm, ông dạo
chơi ở Mão Hồ về phương đông, bỗng gặp một
ngôi chùa làng có pho tượng Quán Âm [đứng
trong chùa mà] bị nước dột thấm ướt hết. Ông
lục trong túi còn được 10 lượng bạc, liền trao
hết cho thầy trụ trì để tu sửa mái chùa. Thầy
trụ trì nói việc này tốn kém nhiều mà tiền như
vậy quá ít, e không thể làm được. Bao Bằng
liền lấy ra bốn xấp vải Tùng,^[Vải Tùng: loại vải đặc biệt được sản xuất tại Tùng
Giang.] lại soát trong
rương hành lý được bảy cái áo vải kép loại tốt,
chỉ vừa mới mua, liền trao tất cả cho thầy trụ
trì. Người hầu có ý ngăn cản, Bao Bằng liền
nói: “Chỉ cần thánh tượng Bồ Tát không bị hư
hoại, ta dù không mặc áo cũng chẳng hề gì.”
Thầy trụ trì cảm động rơi nước mắt, nói: “Đem
tiền, vải, áo cúng dường, cũng không phải việc
khó làm, nhưng tâm chí thành như ông thật
không dễ có!”

Khi việc tu sửa ngôi chùa đã hoàn thành,
Bao Bằng lại đưa cha mình cùng đi đến viếng
chùa, nghỉ đêm lại đó. Ông mộng thấy có vị
hộ pháp đến cảm tạ và nói: “Con ông sẽ được
hưởng lộc ở đời.”

Về sau, con trai ông là Bao Biện, cháu nội là
Bao Sanh Phương, đều đỗ đạt làm quan vinh hiển.

* * *

Huyện Gia Thiện [thuộc tỉnh Chiết Giang]
có người tên Chi Lập. Cha ông trước đây là
một viên thư lại giúp việc hình án trong
huyện. Có người tù vô tội nhưng bị hãm hại
phải chịu tội tử hình. Ông thấy vậy thương
xót, muốn tìm cách xin cho được sống. Người
tù [nhân lúc vợ vào thăm] nói với vợ rằng:
“Ông Chi có lòng tốt cứu giúp, tôi thật hổ thẹn
không biết lấy gì báo đáp. Ngày mai nàng hãy
mời ông ấy đến nhà chơi, xin được đem thân
hầu hạ chăn gối. Nếu ông ấy chấp nhận thì
tôi có thể giữ được mạng sống.” Người vợ khóc
mà vâng lời.

Hôm sau, khi ông Chi đến nhà, người vợ
tự mình ra hầu rượu, nói rõ ý chồng mình.
Ông Chi không chấp nhận, nhưng sau đó vẫn
đem hết sức lo liệu sự việc. Khi người tù được
tha, vợ chồng cùng đến nhà ông bái tạ rồi nói:
“Ân đức của ông thật trên đời hiếm có. Nay
biết ông không có con, chúng tôi có đứa con
gái vừa lớn, xin cho được theo làm hầu thiếp
lo liệu việc nhà. Như vậy cũng là theo đúng
lễ nghi.”

Ông Chi liền lo đủ lễ vật mà cưới về. Sau
sinh ra Chi Lập, 20 tuổi đã thi đỗ đầu bảng,
sau làm quan đến chức Khổng Mục trong
Hàn Lâm viện.

Chi Lập sinh con là Chi Cao, Chi Cao sinh
ra Chi Lộc, đều đỗ cử nhân, học vấn uyên bác.
Chi Lộc lại sinh ra Chi Đại Luân thi đỗ tiến
sĩ.^[Chi Đại Luân thi đỗ tiến sĩ vào niên hiệu Vạn Lịch thứ
hai (1574), như vậy ông là người đồng thời và đỗ tiến
sĩ trước Viên Liễu Phàm 12 năm. Ông được bổ làm
quan trải qua nhiều chức vụ, cuối cùng là Tri huyện
Phụng Tân. Ông có để lại nhiều tác phẩm như: Thế
mục lưỡng triều biên niên sử, Chi tử dư tập, Hoa tụy
từ...]

* * *

Mười trường hợp vừa kể trên, việc làm của
mỗi người đều khác biệt, nhưng giống nhau ở
một điểm: tất cả đều là việc thiện. Tuy nhiên,
xét đến chỗ tinh yếu cặn kẽ mà nói thì việc
làm thiện còn có phân ra chân thật khác với
giả dối, ngay thẳng khác với tà vạy, tích âm
đức khác với tạo phước ở đời, đúng đắn khác
với sai lầm, lệch lạc khác với chính đáng, một
phần khác với trọn vẹn, lớn lao khác với nhỏ
nhặt, khó khăn khác với dễ dàng. Hết thảy
đều nên luận xét đến chỗ sâu xa. Nếu làm
việc thiện mà không thấu hiểu cặn kẽ đạo lý,
ắt có khi tưởng mình đang làm việc thiện mà
không biết đó là tạo nghiệp xấu. Như vậy thì
khổ nhọc tâm trí cũng chỉ là uổng phí, chẳng
được ích lợi gì.



**Như thế nào là chân thật khác với giả
dối?**

Xưa có một nhóm các nho sinh đến tham
vấn hòa thượng Trung Phong, thưa hỏi rằng:
“Nhà Phật đưa ra thuyết nhân quả báo ứng
như bóng theo hình, nhưng nay thấy người
kia làm việc thiện mà con cháu họ không được
hưng thịnh, lại thấy người nọ làm việc ác mà
con cháu họ sung túc thịnh vượng. Như vậy,
thuyết của nhà Phật thật chẳng lấy gì để làm
bằng cứ cả.”

Hòa thượng Trung Phong đáp: “Khi cảm
xúc trần tục chưa dứt sạch thì con mắt chân
chánh chưa thể khai mở. Đối với việc thiện
mà xem là ác, đối với việc ác lại xem là thiện,
những việc như thế rất thường gặp. Sao các
ông không tự trách chỗ thấy biết điên đảo sai
lầm của mình mà ngược lại oán trách sự báo
ứng của đạo trời cho là sai lệch?”

Các nho sinh liền hỏi: “Thiện và ác [là hai
điều trái ngược nhau], sao có thể nhận biết
điên đảo như thầy nói?”

Hòa thượng liền bảo họ mỗi người hãy đưa
ra sự mô tả để phân biệt thiện ác.

Một người nói: “Mắng nhiếc, nhục mạ
người khác là ác; cung kính, lễ phép với người
khác là thiện.” Hòa thượng Trung Phong nói:
“Chưa hẳn đã là như vậy.”

Một người khác nói: “Tham muốn tiền
của, làm bậy để lấy của người khác là ác;
ngay thẳng thanh bạch không lừa gạt lấy
của người khác là thiện.” Hòa thượng Trung
Phong lại nói: “Chưa hẳn đã là như vậy.”

Mỗi người trong nhóm nho sinh đều nói
ra cách hiểu của mình, hòa thượng Trung
Phong đều bảo là chưa đúng. Cuối cùng, cả
nhóm cùng thưa thỉnh ngài nói ra lý lẽ đúng
thật.

Hòa thượng bảo họ: “Việc làm mang lại
lợi ích cho người khác, đó gọi là thiện; việc
làm chỉ mưu lợi ích riêng cho bản thân mình,
đó gọi là ác. Nếu có thể mang lại lợi ích cho
người, thì việc mắng nhiếc, nhục mạ người
cũng đều là thiện. Nếu chỉ vì lợi ích riêng tư
cho bản thân mình thì việc cung kính, lễ phép
với người khác cũng đều là ác.

“Vì thế, người làm việc thiện lấy sự lợi
ích cho người khác làm việc chung, thì việc
chung ấy là chân thật; xem lợi ích của bản
thân mình là việc riêng tư, việc [mưu lợi]
riêng tư ấy ắt là giả dối.

“Làm việc thiện xuất phát từ tâm chân
thành là chân thật, không xuất phát từ bản
tâm, chỉ bắt chước làm theo là giả dối.

“Làm việc thiện mà hoàn toàn không vướng
chấp vào hình tướng là chân thật, vướng mắc
nơi hình tướng phân biệt là giả dối.^[Nguyên bản dùng “vô vi nhi vi” (無為而為) và “hữu vi
nhi vi” (有為而為) để phân biệt. Đây là tư tưởng đã
được giảng rõ trong kinh Kim Cang, được mô tả như
là “trụ tướng” và “bất trụ tướng”. Làm thiện theo cách
“vô vi” thì không phân biệt có mình và người khác,
do đó không có sự mong cầu báo đáp, nên tâm thiện
ấy là chân thật. Làm thiện theo cách “hữu vi” thì có
sự so đo tính toán, ắt phải có sự mong cầu báo đáp,
thậm chí còn mong được báo đáp sao cho xứng đáng,
nên tâm thiện ấy là giả dối.]

“Đối với hết thảy những việc tương tự
khác, các ông đều nên [dựa theo các nguyên
tắc nêu trên mà] tự mình khảo xét [phân biệt
giữa thiện hay ác, chân thật hay giả dối].”

**Như thế nào là ngay thẳng khác với tà
vạy?**

Người đời nay thấy những kẻ thật thà dễ
sai bảo thì xem đó là người hiền lành mà chọn
dùng. Bậc thánh nhân [xưa kia] thà chọn
dùng những người có chí khí hướng thiện
hoặc có quyết tâm không làm việc ác.^[Nguyên tác dùng “cuồng quyến” (狂獧). Sách Mạnh
tử, chương Tận tâm, phần Hạ, tiết thứ 37 chép rằng:
“孟子曰：孔子不得中道而與之，必也狂獧乎！狂者
進取；狷者有所不為也。” - Mạnh tử viết: “Khổng
tử bất đắc trung đạo nhi dữ chi, tất dã cuồng quyến
hồ! Cuồng giả tiến thủ, quyến giả hữu sở bất vi dã.”
(Mạnh tử nói: “Khổng tử không tìm được hạng người
theo trung đạo để truyền dạy, ắt phải nhận lấy những
kẻ cuồng quyến thôi. Cuồng là chỉ người có chí khí
tiến lên, quyến là những kẻ quyết không làm điều trái
đạo lý.”) Như vậy, quan điểm của Viên Liễu Phàm có
thể xuất phát từ đây, và thánh nhân mà ông dẫn ra đó
hẳn là Khổng tử. Vì thế, chúng tôi chuyển dịch theo sự
giảng giải của Mạnh tử.] Với
những kẻ thật thà dễ sai bảo, tuy ở trong một
thôn xóm thì có thể xem là tốt, nhưng đối với
nền đạo đức chung thì đó là những kẻ gây tổn
hại [vì chỉ biết thuận theo thế tục chứ không
hề có ý chí hướng thiện].

Cho nên, cách phân biệt thiện ác của người
thế tục đem so với bậc thánh nhân rõ ràng có
sự trái ngược nhau. Từ đó mà suy ra, hết thảy
những sự chọn lựa yêu ghét, lấy bỏ của người
đời cũng đều có sai lầm. Sự phân biệt những
điều phước thiện hay tà ác, họa hại của quỷ
thần cũng đều tương đồng với sự phân biệt
những điều đúng đắn hay sai lầm của bậc
thánh nhân, nhưng lại khác biệt với những
sự phân biệt yêu ghét, lấy bỏ của người đời.

Vì thế, nếu muốn làm thiện tích đức, chắc
chắn không thể tùy theo những điều tai nghe
mắt thấy [của riêng mình], mà phải xuất
phát từ cội nguồn sâu thẳm kín đáo trong
tâm, âm thầm tu sửa gột rửa [dứt sạch mọi
điều tà vạy]. Nếu chỉ còn duy nhất một tâm
nguyện cứu người giúp đời, đó là [làm thiện
một cách] ngay thẳng, chỉ cần khởi lên một
mảy may tâm niệm dối người gạt đời, ắt đó là
[làm thiện một cách] tà vạy; nếu chỉ duy nhất
một tâm nguyện thương người yêu đời, đó là
ngay thẳng, chỉ cần khởi lên một mảy may
tâm niệm giận người hận đời, ắt đó là tà vạy;
nếu chỉ duy nhất một tâm nguyện cung kính
người khác, đó là ngay thẳng, chỉ cần khởi lên
một mảy may tâm niệm bỡn cợt, ắt đó là tà
vạy. Những [lý lẽ phân biệt như thế] đều nên
phân tích khảo xét cho thật kỹ lưỡng.

**Như thế nào là tích âm đức khác với tạo phước ở đời?**  

Những việc thiện mà người đời thấy biết
được, đó là tạo phước ở đời. Những việc thiện
mà người đời không hay biết, đó là tích âm
đức. Tích âm đức thì được trời báo đáp, còn
tạo phước ở đời thì được hưởng tiếng tốt.
Tiếng tốt đó cũng là phước báo vậy. Nhưng
danh tiếng vốn là chỗ đối kỵ với [lẽ tự nhiên
của] tạo vật. Người nào được thọ hưởng danh
tiếng tốt đẹp mà không thực xứng đáng thì
đa phần đều phải chuốc lấy tai họa. Người
nào không có lỗi lầm xấu ác gì mà phải oan
ức nhận lấy tiếng xấu thì con cháu lại thường
được nhanh chóng phát đạt. Sự khác biệt
giữa tích âm đức với tạo phước ở đời thật hết
sức tinh tế, nhỏ nhặt khó thấy.

**Như thế nào là đúng đắn khác với sai lầm?**

Nước Lỗ [vào thời Xuân Thu] có luật định
rằng, người nước Lỗ khi bỏ tiền ra để chuộc
dân nước Lỗ [bị bắt làm nô lệ] từ các nước chư
hầu khác về^[Trong thời Xuân Thu, khi các nước chư hầu đánh
nhau, người dân có thể bị quân nước khác bắt về làm
nô lệ phục dịch, nhưng cho phép chuộc về bằng tiền.
Quy định của nước Lỗ nhằm khuyến khích người dân
nước Lỗ mang tiền đi chuộc nô lệ người nước Lỗ ở các
nước khác về.] đều có thể đến quan phủ [địa
phương] nhận lại số tiền đó. Tử Cống chuộc
người về nhưng không chịu nhận lại tiền.

Khổng tử biết chuyện liền chê trách, nói:
“Trò Tứ^[Tử Cống tên là Tứ. Vì là quan hệ thầy trò nên Khổng
tử gọi Tử Cống bằng tên thật.] làm sai rồi. Bậc thánh nhân làm việc
gì đều [nhắm đến việc] sửa đổi phong tục tập
quán [cho tốt hơn], để dẫn dắt dạy dỗ người
đời những điều có thể làm được, chứ không
chỉ riêng tự thân mình làm. Nay ở nước Lỗ
rất ít người giàu có, đa số là dân nghèo, nếu
[chuộc người về rồi] nhận lại tiền mà xem là
không liêm khiết thì làm sao tiếp tục chuộc
[người khác] nữa? Từ nay về sau [e rằng sẽ]
không còn ai chuộc dân Lỗ [bị bắt làm] nô lệ
ở các nước khác về nữa rồi!”

Lại khi Tử Lộ cứu sống một người suýt
chết đuối, người ấy mang một con trâu đến tạ
ơn, Tử Lộ nhận lấy. Khổng tử biết chuyện vui
mừng nói: “Từ nay nước Lỗ ắt sẽ có nhiều kẻ
[dám liều mình] cứu người chết đuối.”

Nếu theo cách nhìn của người thế tục thì
Tử Cống [chuộc người mà] không nhận lại
tiền là tốt, còn Tử Lộ [cứu người mà] nhận
trâu là xấu. [Thế nhưng] Khổng tử lại khen
Tử Lộ mà chê Tử Cống, cho nên biết rằng việc
làm thiện không xét theo sự việc đang xảy ra,
mà phải xét [đến những ảnh hưởng] lan rộng
ngấm ngầm [theo sau sự việc ấy]; không xét
theo hiện tại nhất thời, mà phải xét về [tác
động] lâu dài; không xét riêng một người, mà
phải xét [đến ảnh hưởng đối với] nhiều người.

Nếu việc đang làm tuy là việc thiện,
nhưng ảnh hưởng lan rộng có hại cho người
khác, thì việc ấy tuy có vẻ như thiện nhưng
kỳ thật lại là sai lầm. Nếu việc đang làm tuy
là bất thiện, nhưng ảnh hưởng lan rộng có
thể cứu giúp người khác, thì việc ấy tuy có
vẻ như bất thiện nhưng kỳ thật lại là đúng
đắn. Ở đây chỉ lấy riêng một ý tiêu biểu là
[thiện và bất thiện] mà luận giải, còn những
ý nghĩa khác như [việc làm] hợp đạo nghĩa lại
giống như phi nghĩa, [việc làm] đúng lễ giáo
lại giống như trái lễ, [việc làm] giữ đúng chữ
tín lại giống như bất tín, [việc làm] từ ái lại
giống như không có lòng từ... hết thảy đều
nên phân biệt chọn lựa cho rõ ràng.

**Như thế nào là lệch lạc khác với chính
đáng?**

Tể tướng Lã Văn Ý^[Lã Văn Ý (1418-1462), tự Phùng Nguyên, hiệu Giới
Am, người Tú Thủy, đỗ tiến sĩ vào niên hiệu Chính
Thống thứ 7 (1442) triều Minh, sau khi mất được vua
ban tên thụy là Văn Ý.] khi mới từ quan về
quê, dân chúng khắp nơi trong nước đều hết
lòng kính ngưỡng, xem như núi Thái Sơn, như
sao Bắc Đẩu. Có một người cùng làng uống
rượu say mắng chửi ông, ông không giận, nói
với người hầu rằng: “Người ấy say rồi, đừng
so đo với hắn.” Rồi đóng cửa lại không quan
tâm đến. Qua năm sau, người ấy phạm tội tử
hình bị giam vào ngục, Lã Văn Ý biết chuyện
lấy làm hối hận, nói: “Phải chi hồi đó ta có
chút lưu tâm việc sai trái của hắn, bắt giao
cho quan phủ trị tội, ắt là hắn phải chịu sự
trừng phạt nhỏ mà có thể ngăn ngừa được tội
ác lớn. Ta khi ấy chỉ muốn giữ lòng nhân hậu,
không ngờ lại nuôi dưỡng cái ác của kẻ ấy cho
đến nỗi thành ra sự việc như hôm nay.” Đó là
có lòng lành nhưng lại thành ra làm việc xấu.

Lại có trường hợp khởi tâm xấu ác nhưng
lại làm được việc tốt lành. Như có nhà kia
hết sức giàu có, gặp năm mất mùa đói kém,
có đám dân cùng khốn cướp lúa thóc nơi chợ
búa ngay giữa ban ngày, báo lên quan huyện
nhưng quan huyện không giải quyết. Những
người kia thấy vậy lại càng phóng túng hơn,
cuối cùng [nhà giàu ấy] liền tự ý bắt giam
[những kẻ cướp], nhờ vậy dân chúng mới
được yên ổn. Nếu không làm thế ắt cả vùng
đều loạn cả.

Cho nên, làm việc thiện là chính đáng, làm
việc xấu ác là lệch lạc, điều ấy thì ai cũng biết.
Nhưng khởi tâm thiện mà làm thành việc xấu
ác, ấy là trong chỗ chính đáng mà thành lệch
lạc; khởi tâm ác mà làm thành việc thiện, ấy
là trong chỗ lệch lạc mà thành chính đáng.
Những điều như thế không thể không suy xét
rõ.

**Như thế nào là một phần khác với
trọn vẹn?**

Kinh Dịch nói: _“Điều thiện không tích
chứa thì không đủ tạo thành danh thơm tiếng tốt; điều xấu ác không tích chứa thì không đủ
gây thành họa diệt thân.”_ Kinh Thư nói: _“Tội
ác của nhà Thương như tiền xâu thành chuỗi,
[không phải chỉ trong một lúc mà thành].”_^[ Nguyên bản Hán văn là: “商罪貫盈.” (Thương tội
quán doanh.) Câu này trích từ kinh Thư, thiên Thái
Thệ, phần thượng, viết đủ là: “商 罪 貫 盈 ，天 命 誅
之.” (Thương tội quán doanh, thiên mệnh tru chi. –
Tội ác của nhà Thương [được tích chứa] như tiền xâu
thành chuỗi, nên mệnh trời bắt phải diệt vong.) Câu
trích ở đây có ý nói tội ác không tức thời hình thành,
mà là sự tích chứa dần dần, trải qua lâu ngày, cũng
như người ta xâu tiền thành chuỗi, phải qua nhiều
ngày dành dụm mới đủ số thành một xâu.]
Cũng như việc tích chứa đồ vật vào vật chứa,
nếu siêng năng tích chứa ắt có ngày sẽ đầy
đủ, trọn vẹn; nếu biếng trễ không tích chứa ắt
chỉ được một phần, không thể chứa đầy trọn
vẹn. Đó là một cách giải thích [về sự khác biệt
giữa một phần hay trọn vẹn].

Lại nữa, ngày xưa có một cô gái đến chùa,
muốn cúng dường nhưng không có nhiều
tiền, chỉ còn vỏn vẹn 2 đồng xu, liền mang
ra cúng hết cho chùa. Vị tăng trụ trì thấy
vậy đích thân làm lễ sám hối cho cô. [Nhờ
công đức ấy, không lâu sau] cô được tuyển
vào cung vua, thọ hưởng giàu sang phú quý.
Cô lại viếng chùa, mang theo một ngàn lượng
bạc đến cúng dường. Vị tăng trụ trì chỉ sai đồ
chúng làm lễ hồi hướng rồi thôi. Cô ấy liền
hỏi: “Ngày trước con cúng dường chỉ có 2 đồng
xu, thầy đích thân làm lễ sám hối cho con.
Nay con cúng dường đến cả ngàn lượng bạc
mà thầy không tự thân làm lễ hồi hướng là
vì sao?”

Thầy trụ trì đáp: “Số tiền trước đây tuy ít
nhưng tâm cúng dường hết sức chân thành,
nếu lão tăng này không đích thân làm lễ sám
hối thì không xứng với công đức ấy. Nay số
tiền cúng dường tuy nhiều, nhưng tâm cúng
dường không được chí thiết như trước, có
người thay ta làm lễ sám cũng đã đủ rồi.”

Như thế, cúng dường một ngàn lượng bạc
[nhưng thiếu tâm thành thì] vẫn chỉ là việc
thiện một phần, mà cúng dường chỉ 2 đồng
xu [với tâm chí thành] được xem là trọn vẹn.

[Lại xét chuyện] Chung Ly truyền pháp
luyện đan cho Lã Tổ,^[Chung Ly tức Chung Ly Quyền, Lã Tổ tức Lã Động
Tân. Đây là 2 vị trong Bát tiên theo truyền thuyết của
Trung Hoa.
] có thể biến sắt thành
vàng. Lã Tổ hỏi: “Cuối cùng rồi vàng có trở lại
thành sắt không?” Chung Ly đáp: “Sau 500
năm sẽ trở lại thành sắt.” Lã Tổ nói: “Như vậy
ắt sẽ làm hại người 500 năm sau, tôi không
muốn làm như vậy đâu.” Chung Ly nói: “Người
tu tiên nhất thiết phải tích chứa đủ 3.000 công
hạnh. Nhưng chỉ một lời này của ông đã trọn
đủ 3.000 công hạnh rồi.” Đây cũng là một cách
giải thích khác.

Lại như người mang tài vật ra cứu giúp
người khác, bên trong không thấy có bản thân
mình là người cứu giúp, bên ngoài không thấy
có người được cứu giúp, khoảng giữa không
thấy có tài vật được mang ra cứu giúp, đó gọi
là [thấu suốt] bản thể của _người thí_ , _vật thí_
và _kẻ nhận thí_ đều không thật, cũng gọi là
tâm thanh tịnh chuyên nhất. Được như vậy
thì một đấu thóc cũng có thể gieo trồng công
đức không bờ bến, một đồng xu cũng có thể
làm tiêu trừ tội lỗi trong ngàn kiếp. Nhưng
nếu như tâm này chưa được rỗng rang thanh
tịnh thì dẫu đến vạn dật^[Dật: đơn vị đo lường cổ, mỗi dật bằng 20 lượng.] vàng ròng [mang
làm việc thiện], phước đức vẫn không đầy
đủ, trọn vẹn. Đây cũng là một cách giải thích
khác.

**Như thế nào là lớn lao khác với nhỏ
nhặt?**

Thuở xưa, Vệ Trọng Đạt là một quan
chức [Hàn Lâm viện], [tự thấy mình] bị bắt
đưa đến âm ty, Diêm chúa sai thư lại trình
lên những ghi chép thiện ác [của Trọng Đạt
đã làm ở dương gian]. Khi so sánh thì thấy
những ghi chép xấu ác [quá nhiều, bày ra]
choáng đầy cả sân, còn việc thiện [thì quá ít],
chỉ [được ghi trên một mảnh lụa cuộn tròn
lại] nhỏ như chiếc đũa. Diêm chúa sai đặt tất
cả lên hai bên đòn cân để so sánh nặng nhẹ,
hóa ra hết thảy những ghi chép xấu ác bày ra
đầy sân kia lại nhẹ hơn cuộn giấy lụa ghi việc
thiện cuộn lại chỉ nhỏ như chiếc đũa.

Trọng Đạt thưa hỏi: “Tôi năm nay chưa đến
40 tuổi, sao có thể nhiều việc xấu ác đến như
thế?”

Diêm chúa đáp: “Một niệm tà vạy khởi lên
đã là xấu ác, không đợi đến lúc ông thực sự
làm.”

Nhân đó, Trọng Đạt lại hỏi xem trong cuộn
giấy lụa kia ghi chép những gì. Diêm chúa đáp:
“Triều đình trước đây huy động rất nhiều dân
công tu sửa cầu đá ở Tam Sơn, ông có dâng sớ
can ngăn việc ấy. Trong đó ghi lại bản sớ của
ông.”

Trọng Đạt thắc mắc: “Tuy tôi có can ngăn
thật, nhưng triều đình không nghe theo thì việc
ấy nào có ích lợi gì, làm sao lại có tác dụng mạnh
mẽ [hơn tất cả những điều xấu ác] như vậy?”

Diêm chúa đáp: “Triều đình tuy không
nghe theo việc ấy, nhưng một ý niệm của
ông khởi lên vốn đã là vì [lo lắng cho] tất cả
muôn dân [nên được như vậy]. Ví như triều
đình chịu nghe theo ông thì tác dụng của việc
thiện ấy lại càng mạnh mẽ hơn thế nữa.”

Cho nên, nếu tâm niệm hướng về khắp cả
muôn người thì dù việc thiện nhỏ cũng thành
lớn lao; nếu chỉ riêng lo cho bản thân mình,
tuy có làm nhiều việc thiện cũng chỉ xem là
nhỏ nhặt.

**Như thế nào là khó khăn khác với dễ
dàng?**

Các vị Nho gia ngày trước dạy rằng: “Muốn
tự chế phục bản thân thì phải khởi đầu từ chỗ
khó chế phục nhất.” Khổng tử bàn về việc tu
sửa đức nhân cũng nói: “Phải khởi sự trước
nhất từ chỗ khó.”

[Muốn khởi đầu từ chỗ khó] ắt phải [học
theo] như ông họ Thư ở Giang Tây, bỏ ra cả 2
năm lương bổng ít oi của mình để thay người
khác nộp tiền phạt lên quan phủ, giúp cho
vợ chồng người ấy được khỏi cảnh chia lìa.
Lại như ông họ Trương ở Hàm Đan, đem hết
số tiền dành dụm khó nhọc trong 10 năm để
thay người khác nộp tiền chuộc thân,^[Trung Hoa xưa tuy không thừa nhận có chế độ nô
lệ nhưng vẫn phổ biến việc viết giấy bán thân, nộp
tiền chuộc thân, thảy đều được quan phủ thừa nhận.
Người bán thân rồi thì trở thành phụ thuộc hoàn toàn
vào chủ mua, không khác gì nô lệ. Nếu muốn được tự
do phải nộp đủ số tiền chuộc thân.] cứu
sống được vợ con người ấy. Những người như
thế đều có thể buông bỏ được điều rất khó
buông bỏ [là quyền lợi của bản thân].

Lại như ông già họ Cận ở Trấn Giang, tuy
tuổi già vẫn chưa có con, nhưng không chấp
nhận lấy một cô gái nhỏ tuổi làm thiếp mà
trả lại cho gia đình người hàng xóm.

Đó là [những trường hợp] nhẫn chịu được
điều khó nhẫn chịu, nên cũng được trời ban
phước sâu dày.

Thông thường, những người giàu có, quyền
thế thì việc tạo công đức thật dễ dàng. Nhưng
nếu dễ mà không chịu làm, đó là tự hủy hoại
chính mình. Những người nghèo khổ muốn
làm việc tạo phước đức đều rất khó khăn,
nhưng khó khăn mà có thể làm được, ấy mới
là điều rất đáng quý.

* * *

Việc tùy duyên cứu giúp người khác có
muôn hình vạn trạng, nhưng lược nói theo
những điểm đại cương thì có thể phân ra
mười loại:

1. Cùng người khác làm việc thiện.
2. Giữ lòng yêu kính đối với người khác.
3. Giúp thành tựu những điều tốt đẹp của
    người khác.
4. Khuyên bảo người khác làm việc thiện.
5. Cứu người khi nguy cấp.
6. Khởi xướng, xây dựng những việc lợi ích
    lớn lao cho cộng đồng.
7. Bỏ tiền của làm việc tạo phước.
8. Ủng hộ và bảo vệ, giữ gìn Chánh pháp.
9. Kính trọng các bậc tôn túc, trưởng
    thượng.
10. Khuyên người khác phải biết tôn trọng
    sự sống, thương yêu quý tiếc mạng sống
    của muôn loài.


**1. Thế nào là cùng người khác làm
việc thiện?**

Thuở xưa vua Thuấn ở chỗ bến sông, nhìn
thấy những người đánh cá đều tranh nhau
chỗ nước sâu nhiều cá, khiến cho những người
già yếu [không đủ sức tranh giành] phải bắt
cá ở những nơi nước cạn, dòng chảy xiết. Vua
Thuấn động lòng thương xót, liền đến nơi ấy
cùng mọi người đánh bắt cá. Khi thấy những
người có ý tranh giành, ngài che giấu việc
xấu ấy, chẳng nói gì đến. Khi thấy những
người biết nhường nhịn người khác, ngài hết
lời ngợi khen, tán dương, rồi cũng làm theo
giống như người ấy. Vua Thuấn làm như vậy
được một năm thì mọi người ở đó đều nhường
nhịn cho nhau những chỗ nước sâu nhiều cá.

Thông minh sáng suốt như vua Thuấn,
nào có khó gì việc nói ra một lời dạy dỗ những
người kia [việc tốt nên làm]? Thế mà ngài
không dùng lời dạy dỗ, lại dùng chính việc
làm của tự thân để cảm hóa, thay đổi người
khác, quả thật là một tấm lòng hiền lương
thương người, chấp nhận khó nhọc.

Chúng ta sống vào đời suy mạt, đừng lấy
chỗ hay giỏi của mình mà lấn áp kẻ khác,
đừng lấy chỗ tốt đẹp của mình mà so sánh
với kẻ khác [để tự cho mình là hơn], đừng cậy
chỗ nhiều tài năng của mình mà gây khó cho
người khác. Nên tự kiểm soát, không phô bày
chỗ tài trí của bản thân, chỉ xem đó như hư
huyễn không thật. Thấy người khác có chỗ
lỗi lầm khiếm khuyết, nên bao dung mà che
giấu giúp họ, một mặt là tạo cơ hội cho họ có
thể hối cải lỗi lầm, một mặt lại khiến họ có sự
e dè kiêng sợ mà không dám buông thả phóng
túng. Thấy người khác có chút ưu điểm nhỏ
dùng được, hoặc việc thiện nhỏ có thể chọn
lấy, thì lập tức từ bỏ [chỗ chưa tốt] của mình
mà làm theo đó, lại nên hết lời ngợi khen
xưng tán, truyền rộng sự tốt đẹp ấy đến với
nhiều người khác.

Từ sáng đến tối, mỗi một lời nói, mỗi một
việc làm đều không vì nghĩ đến bản thân, hết
thảy đều chỉ vì muôn người mà xây dựng cho
thành nề nếp tốt đẹp chung. Đó chính là chỗ
độ lượng của bậc đại nhân, luôn vì lợi ích cho
mọi người [mà không nghĩ riêng cho bản thân
mình].


**2. Thế nào là giữ lòng yêu kính người
khác?**

Bậc quân tử với kẻ tiểu nhân, nếu theo
hình dáng bên ngoài mà xét thì rất dễ lẫn
lộn, chẳng khác nhau mấy, nhưng chỉ duy
nhất khi xét đến chỗ giữ lòng tu dưỡng thì
thiện ác thật khác nhau, rõ ràng phân biệt
như trắng với đen, không thể nhầm lẫn. Cho
nên nói rằng: “Bậc quân tử sở dĩ khác biệt
với người tầm thường chỉ là ở chỗ giữ lòng tu
dưỡng.”

Chỗ tu dưỡng của người quân tử chính là
luôn giữ lòng thương yêu, kính trọng đối với
người khác. Nói chung, trong muôn người ắt
có kẻ thân thích, người sơ giao, kẻ quý hiển,
người hèn kém, kẻ trí tuệ, người ngu si, kẻ
hiền lương, người hư hỏng, phẩm chất cao
thấp tốt xấu chẳng ai giống ai, nhưng tất cả
đều là đồng loại với ta, cùng một bản thể như
ta, sao có thể không thương yêu, kính trọng?

Biết giữ lòng yêu kính muôn người, đó chính
là yêu kính thánh hiền. Có thể thấu hiểu được
chí hướng của muôn người, đó chính là thấu hiểu
được chí hướng của bậc thánh hiền. Vì sao vậy?
Vì chí hướng của bậc thánh hiền là mong muốn
cho nơi nơi, người người đều đạt được những
điều họ mong muốn. Chúng ta thuận theo [chí
hướng đó] mà thương yêu kính trọng, giúp cho
muôn người đều được an ổn, đó chính là vì các
bậc thánh hiền mà mang lại sự an ổn cho người
đời.

**3. Thế nào là giúp thành tựu điều tốt
đẹp của người khác?**

Khi ngọc còn trong quặng đá, mang vất
bừa bãi ắt chẳng có giá trị gì hơn viên ngói
hòn sỏi, nhưng nếu được mài giũa đúng cách,
ắt trở thành ngọc khuê, ngọc chương^[Khuê là một loại ngọc quý, được làm thành dạng
phẳng. Dùng ngọc khuê xẻ đôi ra thành ngọc chương.] quý
giá. Vì thế, khi thấy người khác làm được
một việc thiện, hoặc gặp người có chí hướng
tốt đẹp, hoặc tư chất có thể hướng thiện, đều
nên hết lòng dẫn dắt chỉ bày, giúp cho người
ấy thành tựu được những điều tốt đẹp. Hoặc
vì người ấy mà ngợi khen, trợ lực, hoặc giúp
sức duy trì [những điều tốt đẹp]. Nếu có ai vu
khống người ấy, nên vì họ mà làm rõ, hoặc
cùng chia sẻ nhận lấy những hủy báng, công
kích; cần giúp sức cho đến khi người ấy được
thành tựu vững vàng mới thôi.

Người đời nói chung thường không ưa thích
những ai khác biệt với mình. Người hiền lương
trong thôn xóm thường rất ít, mà những kẻ xấu
ác lại rất nhiều. Cho nên, người hiền lương ở
đời thường rất khó tự mình đứng vững. Hơn
nữa, những kẻ tài ba xuất chúng thường cương
trực thẳng thắn, không quá chú trọng đến
dáng vẻ bên ngoài, do đó thường dễ bị người
đời chỉ trích. Vì thế, việc thiện ở đời thường dễ
thất bại, mà người làm việc thiện lại thường bị
người đời chê bai phỉ báng, chỉ những bậc nhân
hậu hơn người mới ra sức giúp đỡ, trợ lực [cho
người làm việc thiện], cho nên công đức ấy thật
hết sức lớn lao.

**4. Thế nào là khuyên bảo người khác
làm việc thiện?**

Đã sinh ra làm người, ai ai cũng sẵn có
tâm hiền thiện. Nhưng đường đời bôn ba xuôi
ngược nên rất dễ đắm chìm sa đọa [vào nẻo
xấu ác]. Vì thế, khi giao tiếp ở đời, ta nên
khéo léo vận dụng phương tiện để giúp người
khác trừ bỏ những [nhận thức] sai lầm mê
muội. Ví như vì kẻ đang say trong giấc mộng
đêm dài mà giúp cho nhất thời tỉnh mộng, lại
ví như vì kẻ bị vây hãm đã lâu trong khổ đau
phiền não mà cứu thoát đưa đến nơi mát mẻ
trong lành. Ân huệ đó thật lớn lao không gì
bằng.

Hàn Dũ nói: _“Khuyên dạy người khác
trong nhất thời thì dùng lời nói, khuyên dạy
người đến trăm đời sau thì viết sách.”_ Nếu so
với việc [tự thân mình] cùng người khác làm
việc thiện [như đã nói trong phần 1 ở trên] thì
[việc khuyên bảo người khác làm việc thiện]
tuy là có hình thức biểu lộ, nhưng giống như
tùy bệnh cho thuốc, cũng có lúc phát huy tác
dụng, đạt được hiệu quả, nên không thể bỏ đi.
Nếu có lúc dùng lời [khuyên bảo người khác]
mà không hiệu quả, [ngược lại còn] đánh mất
đi [quan hệ với] người khác, thì phải quay lại
tự xét trí tuệ của mình [vì chưa đủ sự khéo
léo].

**5. Thế nào là cứu người khi nguy cấp?**

Người đời ai cũng có những lúc nguy cấp
hoạn nạn. Nếu gặp những trường hợp ấy, nên
xem như hoạn nạn nguy cấp đang xảy ra cho
chính bản thân mình, phải nhanh chóng cứu
giúp giải nguy. Hoặc dùng lời nói giúp người
sáng tỏ sự oan ức, hoặc tìm đủ mọi phương cách
mà cứu giúp sự hoạn nạn nguy cấp của người.

Thôi tử nói: _“Ân huệ không phải quý ở sự
nhiều ít, mà giúp người vào lúc nguy cấp mới là
quan trọng.”_ Quả thật là lời nhân hậu biết bao!

**6. Thế nào là khởi xướng, xây dựng
những việc lợi ích lớn lao cho cộng
đồng?**

Ở phạm vi nhỏ thì như trong một xóm thôn,
ở phạm vi lớn hơn thì như trong một quận
huyện, nếu thấy bất kỳ việc gì có lợi ích chung
thì rất nên khởi xướng, xây dựng. Đó là những
việc như đào mương dẫn nước, đắp đê ngăn lũ,
hoặc tu sửa đường sá, cầu cống để thuận tiện
cho kẻ đi đường, hoặc cung cấp cơm ăn nước
uống để cứu giúp người lúc đói khát... Đối với
những việc ấy, nên tùy hoàn cảnh mà khuyên
bảo, khuyến khích mọi người cùng nhau góp
sức làm. [Khi đã làm thì] chẳng sợ kẻ khác
hiềm nghi, chẳng nề hà gian khó.

**7. Thế nào là bỏ tiền của làm việc tạo phước?**  

Sự tu tập theo đạo Phật có hàng vạn thiện
hạnh, trong đó hạnh bố thí được xem là trước
nhất.^[Trong sáu pháp ba-la-mật của hàng Bồ Tát thì Bố thí
ba-la-mật cũng được đề cập trước tiên: Bố thí, Trì
giới, Nhẫn nhục, Tinh tấn, Thiền định và Trí tuệ.] Nói đến hạnh bố thí, chỉ cần một từ
buông xả là trọn đủ. Bậc đạt đạo thì trong
tâm buông xả sáu căn, bên ngoài buông xả
sáu trần,^[Sáu căn, bao gồm: mắt, tai, mũi, lưỡi, thân và ý. Sáu
trần là đối tượng của sáu căn, bao gồm: hình sắc, âm
thanh, mùi hương, vị nếm, sự xúc chạm và các pháp.
] cho đến hết thảy những vật sở
hữu của mình, không có gì là không buông
xả. Người chưa đạt được đến mức ấy thì trước
tiên phải buông xả tiền bạc, mang ra bố thí.
Người đời nhờ có cơm ăn áo mặc mà duy trì
mạng sống, nên xem tiền bạc là quan trọng
nhất. Chúng ta từ nơi chỗ [quan trọng nhất]
đó mà buông xả thì bên trong trừ được sự keo
kiệt bủn xỉn của chính mình, bên ngoài cứu
giúp được sự cần kíp của người khác.

Lúc mới bắt đầu [làm việc bố thí] thường
phải có sự cố gắng, khiên cưỡng, nhưng [tập
quen nhiều lần thì] cuối cùng sẽ trở nên phóng
khoáng, tự nhiên. Bố thí là phương pháp hay
nhất để dứt sạch lòng vị kỷ, trừ hết sự bám
chấp tham tiếc.

**8. Thế nào là ủng hộ và bảo vệ, giữ gìn
Chánh pháp?**

Chánh pháp là con mắt sáng giúp chúng
sinh muôn đời có thể nhìn thấy [con đường
thoát khổ]. Không có Chánh pháp, con người
làm sao [có thể biết thuận theo] trời đất để
góp phần vào cuộc sinh tồn? Làm sao có thể
giáo hóa thành tựu cho muôn loài? Làm sao
có thể thoát ly khỏi mọi sự mê hoặc, trói buộc
trong đời sống thế tục? Làm sao có thể nhập
thế tu sửa cải thiện cuộc đời, xuất thế vượt
thoát luân hồi sinh tử?

Vì thế, mỗi khi gặp những nơi thờ kính các
bậc hiền thánh, những kinh sách giáo pháp,
chúng ta đều phải cung kính tôn trọng mà
sửa sang, trang hoàng cho tốt đẹp. Đến như
việc nêu cao và rộng truyền Chánh pháp, báo
đáp ơn Phật thì lại càng phải hết lòng dốc
sức.

**9. Thế nào là kính trọng các bậc tôn
túc, trưởng thượng?**

Nói đến các bậc tôn túc, trưởng thượng thì
trong phạm vi gia đình có cha mẹ, anh chị,
trên phạm vi đất nước có các vị quan chức,
nhà cầm quyền, cho đến trong phạm vi toàn
xã hội thì hết thảy những người cao tuổi,
người đức độ, người ở cương vị cấp trên hoặc
người có sự hiểu biết cao rộng, chúng ta đều
nên có sự lưu tâm tôn kính phụng sự.

Khi phụng sự cha mẹ ở nhà, phải hết sức
giữ lòng yêu kính, dáng vẻ phải vui tươi, nói
năng phải nhỏ nhẹ từ tốn. Tập quen như vậy
sẽ trở thành tính cách hòa nhã tự nhiên, ấy
là yếu tố căn bản có thể cảm động lòng trời.

Khi bước ra xã hội phụng sự đất nước,
dù làm bất cứ việc gì cũng phải tự mình cẩn
trọng, không vì cấp trên không biết mà tự
ý buông thả làm bậy. Nếu ở cương vị xét xử
người khác, không vì cấp trên không biết mà
tự ý ra oai hà hiếp người khác. Người xưa có
câu: “Phụng sự đất nước như thờ kính trời
đất.” Đó là những chỗ liên quan chặt chẽ đến
âm đức [của con người]. Cứ thử xem qua gia
tộc của những người giữ lòng trung hiếu, ắt
thấy rõ không nhà nào là không có con cháu
hưng thịnh, phát đạt lâu dài. Cho nên nhất
thiết phải thận trọng đối với việc này.

**10. Thế nào là biết tôn trọng sự sống,
thương yêu quý tiếc mạng sống của
muôn loài?**

Con người nhờ có lòng trắc ẩn mới xứng
đáng được gọi là người. Muốn có lòng nhân
hậu, trước tiên phải có lòng trắc ẩn; muốn
tích chứa phước đức, trước tiên phải tích chứa
lòng trắc ẩn. Sách Chu lễ nói: _“Trong tháng
mạnh xuân, tế lễ không được dùng những con
vật giống cái.”_^[Vì tháng mùa xuân các giống vật phần lớn đang mùa
sinh sản, sợ rằng dùng những con vật giống cái để tế
lễ sẽ giết chết cả cái thai trong bụng nó.] Mạnh tử nói: _“Người quân
tử lánh xa chỗ bếp núc.”_^[Vì nhà bếp là nơi giết mổ loài vật nên tránh xa để
không tận mắt nhìn thấy.
] Những điều như
thế đều là để giữ gìn tấm lòng trắc ẩn, [biết
thương tiếc sự sống của muôn loài]. Cho nên,
người xưa có bốn loại thịt tránh không ăn. Đó
là: (1) thịt con vật nghe tiếng kêu khi bị giết,
(2) thịt con vật nhìn thấy khi bị giết, (3) thịt
con vật do chính mình nuôi dưỡng, (4) thịt
con vật người khác cố ý giết để đãi mình.

Người học đạo nếu chưa thể hoàn toàn
dứt bỏ việc ăn thịt thì cũng nên khởi đầu từ
việc tránh ăn những loại thịt như trên, dần
dần tu tiến, tâm từ bi được nuôi dưỡng lớn
mạnh hơn, khi ấy không những có thể giữ
giới không giết hại, mà [còn có thể nhận thức
sâu xa rằng] hết thảy các loài sâu bọ, côn
trùng, động vật... đều có sự sống, cần phải
tôn trọng. Những việc như luộc kén tằm kéo
tơ, cày bừa ruộng đất làm chết côn trùng...
đều là giết hại, mà cơm áo của chúng ta có
được là từ những việc như thế, cho nên cũng
chẳng khác nào giết hại loài khác để giành
lấy sự sống cho chính mình. Hiểu được như
thế thì mới thấy rằng sự hoang phí lương
thực, vật dụng... cũng không khác gì tội giết
hại. Cho đến những việc như lỡ tay làm chết,
giẫm chân đoạt mạng [côn trùng], thật không
thể biết được đã nhiều đến mức nào, nên phải
hết sức đề phòng, hạn chế. Cổ thi có câu rằng:

>Lưu hạt cơm thừa, thương chuột đói,  
>Giữ mạng thiêu thân, chẳng đốt đèn.^[Hai câu thơ này của đại thi hào Tô Đông Pha, nguyên văn chữ Hán là: 愛鼠常留飯，憐蛾不點燈 - (Ái thử thường lưu phạn, lân nga bất điểm đăng.) Đại ý nói rằng, vì thương loài chuột bị đói nên khi ăn để lại ít cơm thừa rơi rớt mà không dọn sạch; vì không muốn loài thiêu thân phải chết vì lao vào ngọn lửa nên không đốt đèn.]

Thật nhân từ biết bao!

* * *

Thiện hạnh có rất nhiều, không thể kể hết
ra được, nhưng từ nơi mười điều vừa nói trên
đây mà suy xét rộng ra, thì muôn ngàn công
đức đều có thể đầy đủ cả.

