# Giữ đức khiêm hạ {- #giu-duc-khiem-ha}

Kinh Dịch nói: “Đạo của trời
thường bớt những chỗ dư thừa
mà bù đắp chỗ khuyết thiếu; đạo của đất
thường làm thay đổi chỗ tràn đầy mà giữ
nguyên chỗ khuyết thiếu; quỷ thần thường
gây hại nơi sung mãn mà ban phúc nơi khiêm
hạ; lòng người thường ghét kẻ cao ngạo mà
yêu thích kẻ khiêm hạ.”

[Trời đất, quỷ thần với con người đều
chuộng đức khiêm hạ,] vì thế nên [trong kinh
Dịch] chỉ riêng một quẻ Khiêm là cả 6 hào
đều tốt lành.

Kinh Thư nói: “Sung mãn thường chuốc
lấy tổn hại, khiêm hạ được nhận lãnh ích lợi.”

Tôi đã nhiều lần cùng những người khác
đi thi, mỗi khi gặp kẻ học trò nghèo sắp đỗ
đạt đều thấy có dáng vẻ khiêm hạ lộ rõ ra bên
ngoài.

Vào năm Tân Mùi,^[Tức là năm 1571. Khoa thi này Viên Liễu Phàm không
đỗ.] trong số cử nhân về
kinh đô dự thi thì nhóm đồng hương Gia
Thiện chúng tôi có 10 người. Đinh Kính Vũ là
người nhỏ tuổi nhất, tính tình hết sức khiêm
hạ. Tôi có nói với Phí Cẩm Pha: “Anh này
năm nay ắt sẽ thi đỗ.”

Họ Phí hỏi lại: “Làm sao biết được?”  

Tôi đáp: “Chỉ người khiêm hạ mới được
nhận lãnh phước báo. Anh xem trong số
chúng ta có ai thật thà chất phác, nhường
nhịn không tranh giành như Kính Vũ chăng?
Có ai giữ lòng cung kính vâng chiều, hết lòng
khiêm hạ như Kính Vũ chăng? Có ai bị người
hà hiếp không cần đáp trả, bị người chê bai
không cần biện giải như Kính Vũ chăng?
Người được như thế ắt trời đất quỷ thần
thường trợ giúp, sao có thể không vươn lên
được?”

Đến khi yết bảng, quả nhiên Kính Vũ
trúng tuyển.

Vào năm Đinh Sửu^[Tức là năm 1577.] tôi về kinh đô, cùng
ngụ một chỗ với Phùng Khai Chi, nhận thấy
ông này tính tình khiêm hạ, dung mạo nghiêm
trang, phần lớn là do đã rèn luyện quen từ
thuở nhỏ. Khi ấy có Lý Tễ Nham là người bạn
tốt, tính tình thẳng thắn, thường nhiều lần
công khai phê phán chỉ trích những điều sai
lầm của Khai Chi, chỉ thấy anh ta bình tĩnh
lắng nghe và nhận chịu, chưa từng có một
lời phản đối. Khi ấy tôi có nói với Khai Chi
rằng: “Phước báo đều có căn nguyên, tai họa
cũng có nguồn gốc từ trước. Tâm mình thực
sự khiêm hạ ắt trời sẽ giúp. Năm nay nhất
định anh sẽ thi đỗ.” Quả nhiên đúng như vậy.

Ông Triệu Dụ Phong, tên Quang Viễn,
là người huyện Quan thuộc tỉnh Sơn Đông,
tuổi còn trẻ đã thi đỗ cử nhân ở kỳ thi Hương,
nhưng rất lâu sau [thi Hội nhiều lần] chẳng
đỗ. Cha ông được bổ làm quan Chủ Bạ^[Nguyên bản dùng Tam Doãn (三尹), là cách gọi trang trọng của chức quan Chủ Bạ, đứng đầu phụ trách
công việc văn phòng.] ở huyện Gia Thiện, ông theo cha đi nhậm chức.
Vì ngưỡng mộ [văn tài] của Tiền Minh Ngô
nên ông mang bài văn của mình đến cho họ
Tiền xem. Tiền Minh Ngô xem qua rồi liền sổ
toẹt hết cả bài. Triệu Dụ Phong chẳng những
không giận mà còn hết lòng khâm phục,
nhanh chóng tự sửa đổi. Năm sau ông liền
thi đỗ.

Vào năm Nhâm Thìn,^[Tức là năm 1592.] ta đến kinh thành
triều kiến, nhân lúc đó được gặp Hạ Kiến Sở.
Ta thấy ông này thần khí khoan thư không tự
mãn, tâm ý khiêm hạ, vẻ nhún nhường lộ rõ
ai cũng thấy. Lúc về, ta có nói với bạn bè rằng:
“Thông thường khi trời sắp giúp một người nào
hưng khởi thì khi chưa ban phúc đã trước hết
làm cho người ấy phát khởi trí tuệ. Một khi trí
tuệ phát khởi thì người hư huyễn bỡn cợt sẽ
trở nên chân thành tín thật, người phóng túng
buông lung sẽ tự biết kiềm chế, thu liễm. Ông
Kiến Sở hòa nhã hiền lành như thế, ấy là đã
được trời khai mở [trí tuệ] rồi, [ắt nay mai sẽ
được ban phúc].”

Đến khi yết bảng, Hạ Kiến Sở quả nhiên
thi đỗ.

Trương Úy Nham người huyện Giang Âm,
học nhiều biết rộng, có danh trong giới văn
chương. Vào năm Giáp Ngọ,^[Tức là năm 1594.] ông về Nam
Kinh thi Hương, ở trọ trong một ngôi chùa.
Đến khi niêm yết kết quả thi không thấy
tên mình trúng tuyển, ông hết lời chửi mắng
quan chủ khảo, cho là có mắt không tròng.
Bấy giờ có một đạo sĩ đứng gần đó bật cười.

Họ Trương lập tức quay sang nổi cơn thịnh
nộ với đạo sĩ.

Đạo sĩ nói: “Văn của ông chắc chắn là
không hay rồi.”

Họ Trương càng sôi giận hơn, quát nạt:
“Ông chưa từng đọc văn của tôi, sao biết là
không hay?”

Đạo sĩ nói: “Tôi nghe rằng, người làm văn
quý nhất ở chỗ tâm ý khí chất ôn hòa bình
thản, nay nghe ông chửi mắng, [tâm ý khí
chất] không có chút ôn hòa bình thản gì cả thì
văn làm sao có thể hay?”

Họ Trương nghe như thế hốt nhiên khâm
phục, liền thi lễ xin được chỉ dạy. Đạo sĩ nói:
“Việc thi đỗ hay không đều do số mạng. Số
mạng của mình không đáng đỗ đạt thì dù văn
hay cũng chẳng ích gì. Nên tự thay đổi chính
mình mới được.”

Họ Trương hỏi: “Đã do số mạng định sẵn
thì làm sao thay đổi?”

Đạo sĩ nói: “Tạo ra số mạng là trời, mà an
lập số mạng là chính mình. Nỗ lực làm thiện,
rộng tích âm đức thì có phước đức nào mà
không cầu được?”

Họ Trương nói: “Tôi chỉ là anh học trò
nghèo, làm sao làm [việc thiện]?”

Đạo sĩ nói: “Việc làm thiện, tích âm đức
đều từ nơi tâm mình mà ra. Thường giữ
tâm [hiền thiện] thì được vô lượng công đức.
Chẳng hạn như việc giữ tâm khiêm tốn nhún
nhường nào có tốn kém tiền bạc gì, sao ông
không biết tự xem lại mình, còn chửi mắng
quan chủ khảo?”

Trương Úy Nham từ đó theo lời dạy, cố tự
sửa đổi, bỏ lòng kiêu mạn mà giữ đức khiêm
hạ, tâm thiện ngày càng tăng trưởng, đức
hạnh ngày một sâu dày. Năm Đinh Dậu,^[Tức là năm 1597.] ông
nằm mơ thấy đi đến một căn phòng trên cao,
nhìn thấy một quyển sổ ghi chép tên người thi
đỗ, trong đó có nhiều hàng bỏ trống, liền hỏi
một người đứng bên cạnh rằng: “Bản danh
sách chép tên người thi đỗ khoa này, sao lại
thiếu nhiều tên như vậy?” Người ấy đáp: “Việc
chọn người đỗ đạt, ở cõi âm cứ 3 năm lại một
lần khảo xét so sánh, những người thường
tích âm đức, không phạm lỗi lầm mới có tên
trong đó. Những dòng bị trống đó đa phần
đều là những người vốn ngày trước đáng được
đỗ đạt, nhưng vì gần đây đức hạnh kém cỏi
nên bị xóa đi.” Sau đó, người ấy lại chỉ vào
một dòng còn trống trong sổ và nói: “Trong ba
năm qua ông luôn biết giữ mình thận trọng,
có thể được ghi tên vào đây, mong ông biết tự
lo cho mình.”

Khoa thi năm ấy quả nhiên Trương Úy
Nham thi đỗ, xếp hạng thứ 105.^[Như vậy ông này đỗ vào hàng Tam giáp, tức Đồng
tiến sĩ xuất thân, vì vào triều Minh chỉ hàng Tam giáp
mới lấy đến số 130 người.]

Do những điều như trên mà biết được rằng,
trên đầu ba thước^[Nguyên văn dùng tam xích (三尺), tức 3 thước cổ,
bằng khoảng 1 thước tây. Tuy nhiên, trong thành ngữ
này thì đây chỉ là một con số tượng trưng thôi.] nhất định có thần minh soi
xét. Việc lành dữ, tốt xấu chắc chắn đều do
chính mình, cần phải biết giữ lòng hiền thiện,
kiểm soát mọi việc làm của mình, không một
mảy may phạm vào những điều xấu ác, luôn
khiêm hạ nhún nhường, khiến cho trời đất quỷ
thần đều cảm động trợ giúp, như thế mới có
được nền tảng để hưởng phước báu. Người nào
tính khí cao ngạo tự mãn ắt phải là kẻ thiển
cận, ví như có được hưng khởi phát triển cũng
không thể thọ hưởng [lâu dài] được. Người có
chút tri thức hiểu biết ắt không ai chịu rơi vào
chỗ độ lượng hẹp hòi, tự đánh mất đi phước
báu như thế. Huống chi sự khiêm tốn là mở ra
cơ hội học hỏi từ người khác, lại có thể nhận
lấy noi theo việc làm thiện của người, không
có giới hạn.

Người cầu công danh sự nghiệp lại càng
không thể thiếu sự khiêm hạ. Lời xưa có câu:
“Có chí hướng công danh, ắt được công danh;
chí hướng sang giàu, ắt được sang giàu.” Người
có chí hướng như cây có gốc rễ. Muốn lập chí
công danh vững vàng phải luôn luôn giữ lòng
khiêm hạ nhún nhường, vận dụng khéo léo vô
số phương tiện [mà làm việc thiện], tự nhiên
sẽ cảm động thấu cả đất trời. Cho nên, phước
đức đều do chính mình tự tạo.

Người đời nay muốn cầu thi cử đỗ đạt
nhưng khởi đầu thường không có chí hướng
chân thật, bất quá chỉ là sự hứng khởi trong
nhất thời mà thôi. Lúc có hứng khởi thì mong
cầu, lúc không còn hứng khởi ắt cũng thôi
không mong cầu nữa. Mạnh tử nói [với vua
nước Tề]: “Nhà vua hết sức yêu thích âm
nhạc, nước Tề sắp thịnh vượng rồi.”^[Đoạn trích này lấy từ sách Mạnh tử, chương Lương Huệ Vương, phần Hạ. Đây là lời Mạnh tử nói với Tề
Tuyên vương, nhân khi vị vua này cho biết mình rất
yêu thích âm nhạc. Trong cuộc đối thoại này, Mạnh
tử liên kết sự yêu thích âm nhạc của vua với việc cai
trị đất nước và nêu ra nguyên tắc chính yếu là: Nếu
vua vui thích với việc nghe âm nhạc mà có thể làm
cho toàn dân cùng chung vui với mình thì đất nước
sẽ được thịnh vượng.] Ta đối với con đường công danh khoa bảng cũng
giống như vậy.^[Ý của tiên sinh Viên Liễu Phàm ở đây là, khi mình
cầu công danh sự nghiệp cũng phải biết hướng đến
việc chung trong cộng đồng, nỗ lực làm thiện tích
đức là làm lợi ích cho nhiều người. Làm được như thế
thì bản thân mình đạt được mong muốn mà nhiều
người khác cũng đều vui theo, cũng 
giống như theo
lời Mạnh tử, nếu vua Tề vui với âm nhạc mà biết làm
cho dân chúng nước Tề đều được vui theo thì đất
nước nhất định sẽ thịnh vượng.]
