# Sơ lược tiểu sử Viên Liễu Phàm  {- #so-luoc-tieu-su-vien-lieu-pham}

Viên Liễu Phàm sinh năm 1533,
trước có tên là Viên Biểu, sau đổi
thành Viên Hoàng, tự Khôn Nghi, cũng có
tên tự là Khánh Viễn; trước lấy hiệu là Học
Hải, sau đổi hiệu là Liễu Phàm.

Tổ tiên họ Viên vốn cư ngụ ở phủ Gia
Hưng, tỉnh Chiết Giang, vào cuối đời Nguyên
là một gia tộc hết sức giàu có. Sang đầu triều
Minh, Yên Vương Chu Lệ cướp ngôi của cháu
mình là Chu Doãn Văn, tự lên làm hoàng
đế, xưng là Minh Thành Tổ. Khi ấy có một
số người phản đối, bị Minh Thành Tổ truy
bắt giết sạch. Tổ tiên họ Viên vì có giao du
với những người chống đối nên cũng bị truy
bắt, may mắn chạy thoát được nên phải lưu
lạc khắp nơi, sau đến ngụ ở Nam Trực, thuộc
huyện Ngô Giang, phủ Tô Châu, tỉnh Giang
Tô.

Đến đời Viên Liễu Phàm cưới vợ người
huyện Gia Thiện rồi đến ở rể, hóa ra lại quay
về quê cũ của tổ tiên là phủ Gia Hưng, tỉnh
Chiết Giang.

Tiên sinh Viên Liễu Phàm rất chú trọng
phép tĩnh tọa dưỡng sinh. Ông có để lại 2 tác
phẩm nổi tiếng về chủ đề này là Nhiếp sinh
tam yếu và Tĩnh tọa yếu quyết. Sách Tĩnh
tọa yếu quyết có 3 thiên: Dự hành, Tu chứng,
và Điều tức. Thiên Dự hành giới thiệu những
điều cần yếu của người luyện tĩnh tọa, trọng
điểm là điều tâm, hệ duyên thu tâm, tá sự
luyện tâm, tĩnh xứ dưỡng khí, náo xứ luyện
thần. Thiên Tu chứng thảo luận sự tự thể
nghiệm của việc tọa thiền. Thiên Điều tức
giới thiệu 3 phương pháp điều tức của Phật
giáo.

Tiên sinh viết sách _Liễu Phàm tứ huấn_
vào khoảng năm 1601 (69 tuổi). Ban đầu, đây
chỉ là những lời răn dạy được ông viết ra cho
con trai là Viên Thiên Khải năm ấy vừa được
20 tuổi, nên được ông gọi là Giới tử văn (Bài
văn răn dạy con). Về sau, sách được lưu hành
hết sức rộng rãi khắp nơi, nên người đời sau
đổi tên lại là Liễu Phàm tứ huấn (Bốn điều
khuyên dạy của tiên sinh Liễu Phàm).

Cha ông mất sớm, mẹ ông khuyên theo học
nghề thầy thuốc. Sau, ông gặp tiên sinh họ
Khổng người Vân Nam truyền cho phép toán
số Hoàng Cực của Thiệu Khang Tiết và đoán
số mạng suốt đời cho ông. Ông nghe lời họ
Khổng bỏ nghề thuốc, ra công học tập để cầu
công danh sự nghiệp. Niên hiệu Long Khánh
thứ ba (1569), ông gặp được Thiền sư Vân Cốc
ở núi Thê Hà, Kim Lăng. Thiền sư dạy ông
đạo lý làm thiện tích đức có thể chuyển đổi
số mạng. Ông như người ngủ mê chợt tỉnh, từ
đó liền đổi hiệu Học Hải thành Liễu Phàm để
ghi nhớ cuộc gặp gỡ này và thuyết tự lập số
mạng vừa học được. Ông tự nguyện từ đó về
sau quyết không rơi vào cách nghĩ cách làm
thông thường của người phàm tục.

Sang niên hiệu Long Khánh thứ tư (1570),
ông thi đỗ cử nhân. Niên hiệu Vạn Lịch thứ
14 (1586) ông đỗ tiến sĩ, được bổ làm Huyện
lệnh huyện Bảo Để, sau thăng làm Chủ sự ở
Ty Chức Phương thuộc bộ Binh. Ông tham
gia cuộc chiến tranh với quân Nhật tại Triều
Tiên, từng chỉ huy đẩy lùi quân Nhật.

Niên hiệu Vạn Lịch thứ 21 (1593), vào
ngày 27 tháng Giêng, cũng trong cuộc chiến
tranh với quân Nhật xảy ra trên đất Triều
Tiên, Lý Như Tùng cầm quân tại Bách Đề
Quán bị thua to. Binh bộ Thượng thư lúc ấy
là Thạch Tinh vốn chủ trương nghị hòa. Viên
Liễu Phàm tán thành việc Thượng thư Thạch
Tinh chỉ trích cách cầm quân của Lý Như
Tùng. Do đó, Tùng để tâm oán hận.

Thời gian sau, Lý Như Tùng sàm tấu lên
triều đình, gán cho Viên Liễu Phàm 10 điều
tội danh. Liễu Phàm vì việc đó bị bãi chức về
quê.

Ông mất ở quê nhà vào năm 1606. Đến
niên hiệu Thiên Khải thứ ba (1623), vụ án
oan của ông mới được làm sáng tỏ. Ông được
quan Lại bộ Thượng thư là Triệu Nam Tinh
truy tặng quân công và triều đình truy phong
cho ông là Thượng Bảo Ty Thiếu Khanh.
