# (PART\*) CHUYỆN DU TỊNH Ý GẶP THẦN BẾP {-}

# Làm lành gặp dữ? {- #lam-lanh-gap-du}

Trong khoảng niên hiệu Gia Tĩnh
triều Minh,^[Niên hiệu Gia Tĩnh (嘉靖) là thời gian trị vì của Minh
Thế Tông, kéo dài 45 năm, từ năm 1522 đến năm
1566.] có người họ Du ở tỉnh Giang Tây, tên húy là Đô, tên tự là
Lương Thần,^[Theo những chi tiết được kể trong phần sau thì ông
sinh vào năm 1525, mất vào năm 1612. Ông tự cho
mình tài cao học rộng, chắc chắn sau này sẽ là bậc
rường cột của triều đình nên lấy hiệu là Lương Thần.] kiến thức uyên bác lại có nhiều
tài năng. Từ năm 18 tuổi đã thi đỗ tú tài, mỗi
lần vượt qua các kỳ thi đều có thứ hạng cao.

Thời tuổi trẻ, nhà nghèo nên Du Đô mở
lớp nhận học trò, lại cùng các bạn đồng học
khoảng hơn mười người thành lập nhóm Văn
Xương Xã, [khuyến khích nhau] thực hành
những việc như giữ gìn kính tiếc [giấy có] chữ
viết, phóng sinh cứu vật, răn ngừa những sự
tham dâm, giết hại, nói dối...^[Nhóm người tham gia Văn Xương Xã lấy việc thực hành lời dạy của Văn Xương Đế quân trong bài Âm chất văn
làm mục đích, vì thế lấy tên là Văn Xương Xã.] Thực hành như
vậy được nhiều năm. Trước sau ông đã tham
dự đến 7 khoa thi Hương nhưng đều không
đỗ [lên cử nhân].

Ông Du Đô sinh được 5 đứa con trai thì
có đến 4 đứa bị bệnh chết sớm. Còn lại đứa
thứ ba rất thông minh tuấn tú, dưới lòng bàn
chân trái có 2 nốt ruồi, vợ chồng ông hết sức
yêu quý. Đến năm lên 8 tuổi, đứa con trai
ấy đi chơi trong làng bỗng lạc mất không về,
chẳng biết đi đâu. Ông sinh được 4 đứa con
gái cũng chỉ còn lại một. Vợ ông thương khóc
con đến nỗi mù cả hai mắt.

Ông Du Đô vất vả quanh năm nhưng ngày
càng nghèo túng hơn. Ông thường tự xét mình
không phạm tội lỗi gì lớn, chẳng biết vì sao bị
trời trừng phạt nặng nề bi thảm đến như vậy.

Từ năm ông Du Đô được hơn 40 tuổi, mỗi
năm đến cuối tháng chạp đều tự tay viết một
tờ sớ trên giấy vàng [kể lể than vãn về gia
cảnh của mình], cầu khẩn với thần Bếp xin
chuyển đạt lên [Ngọc đế]. Đã nhiều năm như
vậy nhưng chẳng thấy kết quả gì.
