# Thần Bếp giáo huấn {- #than-bep-giao-huan}

Cho đến năm 47 tuổi, vào đêm giao
thừa cuối năm, ông Du Đô đang
ngồi trong nhà với đứa con gái và người vợ
mù, [cảnh nhà túng quẫn nên] cả nhà đều
buồn bã, thê lương tĩnh lặng, không khí ngập
tràn đau thương chua xót. Bỗng nghe có tiếng
gõ cửa, ông liền cầm đuốc đi ra xem, nhìn thấy
một người mặc y phục màu đen, đầu đội khăn
vuông kiểu đạo sĩ, râu tóc xem chừng đã vào
khoảng năm, sáu mươi tuổi. Người ấy chắp
tay vái chào rất lịch sự rồi [đi theo vào nhà]
ngồi xuống, tự giới thiệu mình là người họ
Trương, từ xa đến đây, nghe biết nhà ông có
chuyện buồn khổ nên đặc biệt tìm đến an ủi.  

Ông Du Đô thấy người khách có vẻ lạ
thường nên thi lễ hết sức cung kính. Nhân khi
trò chuyện, liền kể với ông khách họ Trương
việc mình suốt đời đọc sách thánh hiền, làm
thiện tích đức, nhưng đến nay đường công
danh chẳng được như ý, vợ con không trọn
vẹn, cơm ăn áo mặc còn chưa đủ, lại đã nhiều
lần viết sớ nhờ thần Bếp trình lên [Ngọc đế]
nhưng không thấy kết quả gì.

Ông khách họ Trương nói: “Chuyện nhà
ông tôi đã sớm biết từ lâu rồi. Tâm ý xấu ác
của ông thật quá nặng nề. Ông vốn chỉ biết
chạy theo hư danh. Sớ ông viết trình lên chứa
đầy những lời oán hận, xem thường Thượng
đế, tôi chỉ e là sự trừng phạt còn chưa dừng
lại ở mức như hiện nay đâu.”

Ông Du Đô hết sức kinh hãi, thưa rằng:
“Tôi nghe nói trong chốn u minh, dù một điều
thiện nhỏ cũng được ghi chép đủ. Tôi phát
nguyện làm việc thiện, kính cẩn giữ mình
theo khuôn phép [do Văn Xương Xã đề ra] đã
lâu, lẽ nào tất cả những việc ấy đều là chuộng
hư danh thôi sao?”

Ông khách họ Trương nói: “Được, vậy hãy
thử lấy một điều trong những khuôn phép [do
Văn Xương Xã của ông đề ra] mà xét, là việc
giữ gìn kính tiếc [giấy có] chữ viết. Nhóm nho
sinh các ông cùng với những kẻ mà các ông
giao thiệp, hầu hết đều dùng giấy từ sách cũ
để phết dán cửa sổ, bao gói đồ vật, thậm chí
còn dùng để lau chùi bụi bặm trên bàn ghế,
nhưng miệng thì luôn nói chớ làm dơ bẩn giấy,
chỉ nên đốt hết đi. Ông ngày nào cũng nhìn
thấy những việc như vậy nhưng chẳng có một
lời can ngăn răn nhắc, chỉ thỉnh thoảng gặp
vài mảnh giấy giữa đường thì nhặt về đốt đi,
như vậy phỏng có ích gì chăng?

“Lại nữa, trong nhóm Văn Xương Xã của
ông, mỗi tháng đều làm việc phóng sinh, ông
cũng chỉ qua loa làm theo, dựa vào người
khác mà nên việc. Ví như những người khác
không khởi làm thì ông cũng mê muội không
làm, kỳ thật trong lòng ông chẳng có mảy
may tâm niệm từ bi. Hơn nữa, trong nhà ông
các loại tôm cua cũng thường bị đưa vào bếp
nấu nướng, lẽ nào chúng lại không phải sinh
mạng đó sao?

“Mỗi khi có sai trái trong lời nói, ông lại
dùng đến biện tài khéo léo lanh lợi, khiến
cho người nghe phải điên đảo tưởng xấu là
tốt [mà thán phục ông]. Khi ông mở miệng
buông lời, trong lòng vẫn tự biết đang làm
tổn thương đức tốt, chỉ vì quen thói cũ nên
trong lúc cùng bạn bè tụ tập chuyện phiếm cứ
theo đà chê bai, giễu cợt [người khác], không
thể dừng lại được. Miệng lưỡi như thế của
ông khiến quỷ thần phải nổi giận; việc xấu ác
ở cõi âm đã ghi lại thật nhiều chẳng biết đến
bao nhiêu mà kể. Vậy mà ông còn tự nhận
mình là người đức hạnh sâu dày, lại cho rằng
mình chẳng dối lừa khinh dể ai sao? Lại cho
rằng như vậy chẳng phải là khinh dể trời cao
đó sao?

“Còn về chuyện tà dâm, tuy không xảy ra
hành vi thực sự, nhưng ông thấy gái đẹp thì
chăm chăm nhìn kỹ, tâm ý lăng xăng không
còn tự chủ, chỉ là không gặp dịp thích hợp
để hành sự đó thôi. Ông hãy tự xét lại mình
trong những lúc ấy, liệu có được như Lỗ Nam
Tử^[Lỗ Nam tử: nhân vật được nhắc đến trong sách Khổng
tử gia ngữ, là một người nước Lỗ, được khen ngợi là
“suốt đời không vướng chuyện tà dâm háo sắc, có thể
đối mặt cùng trời đất quỷ thần”.
] chăng? Vậy mà dám nói là _“suốt đời
không vướng chuyện tà dâm háo sắc, có thể
đối mặt với trời đất quỷ thần”_ [như Lỗ Nam
tử xưa kia], quả là lời dối trá.

“Đó là những khuôn phép do chính ông
tự nguyện làm theo, [được ghi thành quy củ
điều luật của Văn Xương Xã] mà còn như vậy,
huống chi là những việc khác?

“Ông liên tục nhiều năm đốt sớ trình lên
Thượng đế, kể lể sự tình. Thượng đế lệnh cho
sứ giả Nhật Du xem xét kỹ những việc thiện
ác của ông làm, trải qua nhiều năm không
thấy việc thiện nào có thể ghi nhận, chỉ thấy
những khi ông ở một mình nơi khuất tất
vắng vẻ thì toàn là những tâm niệm tham
lam, dâm dật, ganh ghét, hẹp hòi nóng nảy,
tự mãn khinh người, nhớ việc đã qua, mong
việc sắp đến, báo thù rửa hận... chen nhau
khởi lên trong lòng, [nhiều đến mức] không
thể ghi chép hết. Những sự xấu ác đủ loại
khởi lên từ tâm ý như thế đã tích tụ gắn kết
kiên cố từ lâu, thần minh ghi chép đã nhiều,
trời giáng hình phạt ngày càng nặng, ông dù
muốn tránh né tai họa còn không được thì
dựa vào đâu mà cầu hưởng phước lành?”

Ông Du Đô [nghe qua như vậy] hết sức
kinh hoàng, sợ hãi khôn xiết, quỳ sụp xuống
đất, khóc lóc thưa rằng: “Ngài đã rõ biết hết
những sự việc trong cõi u minh, nhất định là
có quan hệ với tôn thần, cầu xin ngài ra tay
cứu độ.”

Người khách họ Trương liền nói: “Ông là
người đọc sách, hiểu rõ lễ nghĩa, lại cũng biết
hâm mộ điều lành, lấy đó làm vui, nhưng
đang khi nghe [người khác nói] một lời thiện
lại không thể khích lệ, thấy [người khác làm]
một việc thiện lại không thể cổ vũ, chỉ toàn
[phạm vào những điều] lỗi lầm, hư rỗng, [hết
thảy đều do] cội gốc lòng tin chưa tự sâu
vững, tâm tính lại từ lâu đã quen như vậy
nên không hề tự xem xét lại, vì thế mà suốt cả
đời khi nói một lời lành, làm một việc thiện,
[chẳng qua] đều chỉ là phô trương hư huyễn,
chưa từng có lời nào, việc nào là chân thật cả.
Hơn nữa, tâm niệm xấu ác lại chất chứa tràn
ngập trong lòng, tiếp nối nhau không ngừng
sinh khởi, như vậy mà mong muốn được trời
cho phước báo tốt lành thì có khác nào mảnh
đất gieo trồng đầy những gai góc, lại mê muội
mong thu hoạch được lúa tốt, chẳng phải sai
lầm lắm sao?

“Ông từ nay về sau, mỗi khi có những vọng
tưởng tạp niệm như tham lam, dâm dục, giả
dối... thì phải đem hết quyết tâm mạnh mẽ
mà dứt trừ tất cả, thanh lọc [tâm ý sao cho
luôn] trong sạch an tịnh, mỗi mỗi tâm niệm
đều chỉ toàn là hiền thiện. Khi gặp một việc
thiện, nếu thấy sức mình có thể làm được thì
phải mang hết sức ra mà làm ngay, trong
lòng không mong báo đáp, không cầu danh
tiếng, bất kể đó là [việc thiện] lớn hay nhỏ,
khó khăn hay dễ dàng, đều đem tâm chân
thành ham thích nhẫn nại mà làm; nếu thấy
sức mình không thể làm nổi thì cũng phải hết
lòng lưu tâm ân cần khẩn khoản, khiến cho
tâm lành ấy được nuôi dưỡng trọn vẹn.

“Điều cốt yếu thứ nhất là phải có tâm
nhẫn nại, kham chịu, thứ hai là phải có tâm
kiên trì không thối chuyển, nhất thiết không
được biếng lười, nhất thiết phải chân thành
không tự lừa dối. Cứ như vậy mà thực hành
lâu ngày tự nhiên sẽ có những hiệu quả ứng
nghiệm kỳ diệu khôn lường.

“Ta thấy gia đình ông thờ kính ta từ lâu
hết sức chân thành nên mới đặc biệt đến đây
có mấy lời, xem như báo đáp. Ông phải nhanh
chóng làm ngay không nên chậm trễ, may ra
mới có thể chuyển đổi được ý trời.”

Vị khách họ Trương nói xong thì đi thẳng
vào trong nhà. Du công lập tức đứng dậy đi
theo, vừa đến chỗ bàn thờ thần Bếp thì hốt
nhiên không còn thấy đâu nữa, mới biết người
mình vừa gặp chính là ngài,^[Nguyên văn dùng Tư mệnh chi thần (司命之神), là
một danh xưng khác của thần Bếp (Táo quân), gọi
đầy đủ là Đông Trù Tư Mệnh Cửu Linh Nguyên Vương
Định Phước Thần Quân.] liền cung kính đốt hương lạy tạ.
