# Đổi tên Tịnh Ý, chuyển ý thanh tịnh {- #chuyen-y-thanh-tinh}

Hôm sau đó là ngày tết Nguyên
đán, ông Du Đô thiết lễ kính lạy
trời đất, thề nguyện sửa đổi tất cả những lỗi
lầm trước đây, thực hành mọi việc thiện, tự
đổi hiệu mình là Tịnh Ý Đạo nhân, thể hiện ý
nguyện muốn dứt trừ hết mọi sự sai trái xằng
bậy, làm thanh tịnh tâm ý.

Ngày đầu tiên bắt đầu làm thiện, những ý
niệm hỗn tạp đua nhau sinh khởi, nếu không
sinh tâm ngờ vực ắt cũng rơi vào lười nhác uể
oải. Trải qua mấy ngày như thế rồi lại thấy
mình rơi vào chìm nổi mê muội như trước.
Trong nhà có thờ tôn tượng Bồ Tát Quán Thế
Âm, Du Tịnh Ý liền đối trước tượng Bồ Tát
lễ lạy cầu sám hối, khấu đầu đến nỗi chảy
cả máu trán, cung kính phát lời đại nguyện
rằng: _“Con nguyện giữ cho tâm ý chỉ còn
thuần nhất niệm lành, tinh tấn nỗ lực làm
thiện, nếu có mảy may buông lung thối chí,
thề sẽ vĩnh viễn chịu đọa vào địa ngục.”_

Mỗi ngày, vào lúc sáng sớm ông đều kiên
trì xưng niệm danh hiệu Bồ Tát Quán Thế
Âm Đại từ Đại bi để cầu sự gia trì cho mình
[trong việc làm thiện]. Sau đó thì mỗi một lời
nói, mỗi một việc làm, mỗi một ý nghĩ trong
suốt ngày ấy đều tưởng như có quỷ thần đang
ở bên cạnh xem xét, tuyệt nhiên không dám
dối trá lừa lọc, buông thả phóng túng.

Hết thảy những việc gì có thể cứu giúp
người khác, có thể làm lợi lạc cho người, cho
đời, bất kể đó là sự việc lớn hay nhỏ, bất kể
bản thân mình đang lúc bận rộn hay nhàn rỗi,
bất kể là người khác có biết đến hay không,
cũng không ngần ngại suy lường sức lực tự
thân làm nổi hay không nổi, Du Tịnh Ý đều
hoan hỷ cố hết sức làm, cho đến khi thành
tựu mới thôi.

Ông lại tùy nhân duyên phương tiện mà
rộng làm những việc tích lũy âm đức, hơn
nữa còn nỗ lực khuyên người giữ theo luân
thường đạo lý, siêng năng đọc sách học hỏi,
giữ lòng khiêm hạ, nhẫn nhục hòa kính, lại
thường dùng những lẽ nhân quả báo ứng
giảng rộng với mọi người. Ông nỗ lực chuyên
cần làm thiện suốt ngày như vậy nhưng vẫn
không tự cho là đủ.

Vào mỗi ngày cuối tháng, ông Du Tịnh Ý
lại đem hết thảy những lời nói, việc làm trong
suốt tháng đó viết thành một lá sớ đốt trước
bàn thờ thần Bếp để kính cáo.

Ông thực hành như vậy cho đến khi đã
thuần thục thì [đạt đến mức] thân vừa động
ắt có muôn điều thiện tùy theo, tâm vừa tĩnh
ắt không còn một mảy may tạp niệm nào sinh
khởi.

