# Chuyển họa thành phúc {- #chuyen-hoa-thanh-phuc}

Qua ba năm như thế, ông vừa được
50 tuổi, vào niên hiệu Vạn Lịch
thứ hai, triều đình mở kỳ thi Hội năm Giáp
Tuất (1574). Quan Thủ phụ^[Là quan chức cao nhất, đứng đầu triều đình thời nhà
Minh, tương đương chức vụ Tể tướng. Quan Thủ phụ
là người thay vua xử lý việc triều chính, điều hành
mọi hành động của triều đình.] là Trương Giang
Lăng,^[Trương Giang Lăng (張江陵): tên thật là Trương Cư
Chính (張居正), tên tự là Thúc Đại (叔大), hiệu Thái
Nhạc (太岳). Vì ông là người Giang Lăng nên người
thời bấy giờ vẫn thường gọi ông là Trương Giang
Lăng. Ông sinh năm 1525, mất năm 1582, giữ chức
Thủ phụ trong 10 năm, từ 1572 đến 1582.
] sau khi kết thúc kỳ thi liền dò hỏi
những người đồng hương để tìm người làm
thầy dạy cho con. Có người tiến cử Du Tịnh
Ý, quan Thủ phụ liền cho người mời ông đến
kinh đô làm thầy dạy cho con mình.

Khi nghe Du Tịnh Ý kể về những việc mình
đã làm, quan Thủ phụ hết sức kính trọng đức
độ và phẩm hạnh của ông, liền dựa theo quy
định để giúp ông được vào học trường Quốc
học.^[Trường Quốc học ngày xưa là một kiểu trường Đại
học, đào tạo nhân tài, nhưng chỉ ưu tiên dành riêng
cho con em trong hoàng tộc và các quan chức triều
đình. Vì thế, việc ông Du Tịnh Ý được vào học trường
này là một đặc ân.]

Vào niên hiệu Vạn Lịch thứ tư, tức là năm
Bính Tý (1576), ông dự kỳ thi Hương tại kinh
đô, trúng tuyển cử nhân, sang năm sau lại đỗ
tiếp tiến sĩ.

Ngày nọ, ông đến ra mắt quan Nội giám^[Nội giám: tên gọi khác chỉ các quan thái giám, phục vụ trong nội cung.]
họ Dương, ông này gọi năm đứa con nuôi
ra chào. Những người con trai này được họ
Dương nhận từ khắp nơi về nuôi, xem như
con mình và lấy đó làm niềm vui trong tuổi
già. Du Tịnh Ý chợt nhìn thấy trong số đó
có một đứa chừng 16 tuổi, dung mạo dường
như quen thuộc lắm, liền hỏi quê quán. Đứa
trẻ đáp: “Con người tỉnh Giang Tây,^[Nguyên bản chép Giang Hữu (江右), là cách gọi khác của Giang Tây.] thuở
nhỏ đi chơi lên nhầm thuyền buôn gạo [nên
không về nhà được], còn tên họ thời ấy với
tên làng xóm thì chỉ còn nhớ mường tượng
mà thôi.”

Du Tịnh Ý nghe như vậy hết sức ngờ vực,
liền bảo nó cởi giày ra để xem lòng bàn chân
trái, quả nhiên có 2 nốt ruồi rất rõ. Ông mừng
quá hét lớn: “Ôi! Con tôi đây rồi.”

Quan Nội giám họ Dương cũng hết sức
kinh ngạc, lập tức cho đứa trẻ ấy theo Du
Tịnh Ý về chỗ ngụ. Ông hối hả báo tin vui cho
vợ. Vợ ông mừng quá, ôm con khóc lớn đến
nỗi máu từ trong mắt tuôn ra ràn rụa. Đứa
con cũng khóc, rồi nâng niu khuôn mặt mẹ
mà thè lưỡi liếm máu mắt cho mẹ. Không ngờ
lúc ấy bỗng nhiên hai mắt bà sáng lại, nhìn
thấy rõ ràng. Du Tịnh Ý mừng thương lẫn
lộn, không còn muốn làm quan nữa, liền từ
biệt Trương Giang Lăng trở về quê nhà.

Quan Thủ phụ Trương Giang Lăng quý
trọng nghĩa khí của Du Tịnh Ý, gửi biếu
nhiều quà tặng và một số tiền lớn, tiễn ông
về quê.

Về quê nhà, ông càng nỗ lực làm việc thiện
nhiều hơn nữa. Con trai ông sau đó lập gia
đình, sinh được 7 người con, tất cả đều học
hành đỗ đạt thành danh.

Du Tịnh Ý ghi chép lại sự việc mình gặp
thần Bếp cũng như quá trình sám hối sửa lỗi,
dùng để răn dạy, giáo dục con cháu về sau.

Ông sống an ổn khỏe mạnh đến tuổi già,
thọ 88 tuổi. Người đời ai cũng cho rằng đó
là do ông chân thành làm nhiều việc thiện,
chuyển đổi được sự báo ứng trở thành tốt đẹp.

_Kẻ hậu học sống cùng làng với ông Du
Tịnh Ý là La Trinh kính ghi lại câu chuyện
này._
