# Lời bạt {- #loi-bat}

Hai nhân vật, hai cuộc đời được
trình bày trong sách này có khá
nhiều điểm chung. Mặc dù họ xuất thân khác
nhau, đến với đạo Phật cũng qua những nhân
duyên khác nhau, nhưng cả hai đều có đủ
quyết tâm thực hiện đúng theo lời Phật dạy
nên cuối cùng đều đã đạt được một cuộc sống
an vui hạnh phúc ngay trong hiện tại.

Suy ngẫm về cuộc đời của hai nhân vật
này, chắc chắn chúng ta có thể rút ra được
nhiều bài học cho chính bản thân mình. Mặt
khác, khi so sánh cuộc đời của hai người,
chúng ta sẽ thấy được nhiều điều thú vị, bởi
trong khi những điểm tương đồng giữa họ có
thể giúp nhấn mạnh hơn tính đúng thật của
luật nhân quả, thì những điểm khác biệt lại
có thể bổ sung cho nhau để giúp người đọc
có được những hình ảnh minh họa thật khái
quát và rõ nét hơn cho những bài học luân lý
đạo đức được rút ra từ câu chuyện.

Có lẽ sự bổ sung cho nhau cũng là nguyên
nhân chính để những người khắc bản in
_“Liễu Phàm tứ huấn”_ trước đây đã chọn đính
kèm bản văn _“Du Tịnh Ý công ngộ Táo thần
ký”_ vào phần sau, và Đại sư Ấn Quang cũng
tán thành giữ nguyên cấu trúc này khi khắc
in thành phần phụ đính của sách An Sĩ toàn
thư. Thử so sánh một số điểm tương đồng và
khác biệt giữa cuộc đời của hai nhân vật đặc
biệt này, chúng ta sẽ có thể cảm nhận một
cách sâu xa hơn hàm ý của người xưa.

Viên Hoàng xuất thân từ một gia đình
danh gia vọng tộc. Mặc dù tổ tiên ông đã phải
bỏ xứ trốn đi vì sự truy bức của quan quân
do có giao du với người chống đối hành vi
soán ngôi của Yên Vương (Minh Thành Tổ),^[Trong tiểu sử của Viên Liễu Phàm không thấy nói rõ,
nhưng rất có thể người chống đối này chính là Phương
Hiếu Nho (1357 - 1402), người đã quyết liệt chống
đối việc soán ngôi của Yên vương đến nỗi trở thành
người duy nhất trong lịch sử bị tru di 10 họ. Ngoài 9 họ
theo quy định thông thường thì toàn bộ những người
có quan hệ giao du với ông và các học trò, thậm chí là
những người hàng xóm đều bị giết sạch, xem như họ
thứ mười.]
nhưng khi lập nghiệp ở nơi khác, họ vẫn phần
nào giữ được địa vị trong xã hội, và đến đời
Viên Hoàng (1533 - 1606) thì vẫn chưa đến
nỗi hoàn toàn suy kiệt. Chúng ta có thể nhận
ra điều này qua cuộc sống khá an ổn của Viên
Liễu Phàm kéo dài đến hơn 20 năm khi ông
chưa đỗ đạt.

Ngược lại, Du Đô là một hàn sĩ xuất thân
quá ư nghèo khổ, ngay sau khi đỗ tú tài từ
năm 18 tuổi đã phải đối mặt với gánh nặng
cơm áo cho gia đình, đã phải mở trường dạy
học với mục đích đơn giản nhất là nuôi sống
gia đình nhưng gần như vẫn không đạt được.
Vì thế, cuộc sống bi đát của gia đình ông được
mô tả khá rõ nét qua hình ảnh của một đêm
giao thừa khi Tết sắp đến mà _“cả nhà đều
buồn bã, thê lương tĩnh lặng, không khí ngập
tràn đau thương chua xót”_. Hơn thế nữa,
hàng loạt tai họa liên tục giáng xuống gia
đình ông trước đó đã khiến cho vợ ông sau
chín lần sinh nở mà chỉ còn nuôi sống được
hai người con, và rồi đứa con trai cũng thất
lạc từ năm 8 tuổi, chỉ còn lại duy nhất một
người con gái.

Du Đô sinh năm 1525, còn Viên Hoàng
sinh năm 1533, hai người chênh nhau chỉ
8 năm tuổi nên có thể xem như người đồng
thời, có cùng bối cảnh xã hội. Đây cũng là một
yếu tố khiến cho sự so sánh cuộc đời họ càng
thêm thú vị.

Viên Hoàng lấy hiệu là Học Hải, có lẽ muốn
hàm ý là người học rộng, còn Du Đô lấy hiệu
là Lương Thần, nói rõ ý hướng muốn thành
một trụ cột của đất nước, vì tự cho mình là
người tài năng, nhiều tri thức. Cả hai người
đều là những kẻ tài năng nhưng có giai đoạn
đầu đời không thành đạt. Tuy vậy, trong khi
Học Hải chấp nhận an phận với những tiên
đoán của Khổng tiên sinh về một hậu vận
không tốt đẹp, thì Lương Thần lại luôn buồn
phiền, đau khổ với thực trạng nghèo khó và
chịu lắm tai ương, vì cho rằng mình hoàn
toàn không đáng phải chịu như vậy.

Và rồi cả hai người đều thay đổi hoàn toàn
cuộc sống của mình sau một lần gặp gỡ tình
cờ. Viên Học Hải được gặp Thiền sư Vân Cốc,
một nhân vật có thật trong lịch sử, trong khi
Du Lương Thần lại gặp gỡ một nhân vật đầy
kỳ bí mà ông tin chắc là thần Bếp, một vị
thần trong tín ngưỡng dân gian, được gia
đình ông thờ phụng.

Điểm giống nhau giữa hai trường hợp này
là Thiền sư Vân Cốc cũng như thần Bếp đều
là những vị cứu tinh làm thay đổi hoàn toàn
cuộc đời hai người. Các vị đã chỉ ra những suy
nghĩ sai lầm từ trước đó và vạch rõ cho họ một
con đường để thay đổi cuộc đời. Sai lầm của
Viên Học Hải là chỉ biết an phận, chấp nhận
số mạng như một sự an bày và không hề nỗ lực
vươn lên. Trong khi đó, sai lầm của Du Lương
Thần lại là sự mơ hồ giữa thiện và ác, không
hề nhận biết được rằng những tâm niệm xấu
ác giấu kín trong lòng mình chính là nguyên
nhân của khổ đau. Viên Học Hải nhận biết
sai lầm nhưng hoàn toàn thụ động, không hề
có ý hối cải thay đổi, còn Du Lương Thần thì
không tự nhận biết sai lầm nên đem lòng oán
hận trời đất, cho rằng việc nhân quả báo ứng
không hề đúng thật.

Sau khi được Thiền sư Vân Cốc chỉ dạy,
Viên Học Hải đổi tên thành Viên Liễu Phàm,
với ý nguyện dứt bỏ hoàn toàn khuynh hướng
thụ động “quen theo nếp cũ” của những kẻ
phàm tục tầm thường và tự mình nỗ lực tích
cực vươn lên, sửa đổi lỗi lầm để thành người
hoàn thiện. Du Lương Thần thì sau khi được
nghe thần Bếp chỉ ra những tâm niệm xấu
ác giấu kín trong lòng mình đã đổi tên thành
Du Tịnh Ý, với tâm nguyện tự thanh lọc tâm
ý, dứt bỏ hết những ý niệm xấu ác đó để tâm
được thanh tịnh, và dựa trên tâm thanh tịnh
đó để tránh ác làm thiện. Cả hai người đều
thể hiện quyết tâm hối cải, tự sửa đổi bằng
việc đổi tên hiệu.

Trong quá trình tu sửa, Viên Liễu Phàm
đã nghe theo chỉ dạy của Thiền sư Vân Cốc,
áp dụng việc trì tụng thần chú Chuẩn Đề để
giúp an tịnh tâm ý, hỗ trợ cho việc tránh ác
làm thiện. Du Tịnh Ý thì tự mình nhận ra sự
khó khăn trong việc tự lực chuyển đổi tâm ý,
nên đã đặt niềm tin hoàn toàn vào việc lễ bái
tôn tượng Bồ Tát Quán Thế Âm và trì niệm
danh hiệu ngài 100 lần vào lúc sáng sớm để
cầu được sự gia trì, và nhờ đó ông luôn bắt
đầu một ngày mới với tâm an tịnh. Bằng cách
này, ông đã có thể duy trì được quyết tâm
tránh ác làm thiện trong suốt ngày hôm đó.

Để củng cố tâm hành thiện, Viên Liễu
Phàm đã áp dụng phương thức “công quá
cách” của những người đi trước, nghĩa là ghi
chép lại tất cả những điều tốt hoặc xấu của
bản thân nhằm có thể tự theo dõi, nhận biết.
Du Tịnh Ý cũng thực hiện tương tự, nhưng do
ảnh hưởng niềm tin với thần Bếp, ông đã làm
điều này bằng cách viết ra mọi việc thiện ác
trong một lá sớ vào mỗi ngày cuối tháng và
đốt trước bàn thờ thần Bếp để kính cáo. Việc
tự mình ghi chép lại những điều thiện ác có
công năng giúp họ thường xuyên tự xem xét
lại những việc làm đã qua của mình, nhờ đó
luôn sống trong sự tỉnh giác hướng thiện. Vì
thế, cả hai phương pháp này đều đã chứng tỏ
được sự hiệu nghiệm, đều giúp cho hai người
có thể duy trì tâm hướng thiện và tu sửa ngày
càng tốt hơn.

Điểm chung của cả hai người là họ đều tin
vào sự hiện hữu của thần linh, một niềm tin
thuộc tín ngưỡng dân gian chứ không thuộc về
Phật giáo. Đức Phật dạy nhân quả như một
quy luật tự vận hành theo nguyên lý “nhân
nào quả ấy”, phủ nhận hoàn toàn mọi sự ban
thưởng hay trừng phạt của bất kỳ thế lực siêu
nhiên nào. Điều đáng chú ý ở đây là, sự khác
biệt này không hề tạo thành mâu thuẫn trong
niềm tin của đại đa số những người bình dân,
bởi họ tin rằng cho dù luật nhân quả tự nó vận
hành hay do Thượng đế điều hành thông qua
các thần linh thì kết quả vẫn là như nhau, vẫn
dựa trên những tiêu chí thiện ác của những
hành vi mà con người đã tạo tác.

Tính thích nghi hay phương tiện thiện
xảo của đạo Phật chính là ở điểm này. Thay
vì cứng nhắc theo những lời Phật dạy trong
Kinh điển, các bậc thầy tổ khi truyền giảng
giáo lý đạo Phật đã luôn biết tùy thuận theo
những niềm tin sẵn có của quần chúng bình
dân. Thay vì tạo ra mâu thuẫn bằng cách
vạch rõ những khác biệt và phản bác niềm
tin - có thể gọi là mê tín - vào Thượng đế,
thần linh, các ngài đã khéo léo dẫn dắt để
chính Thượng đế hay các vị thần linh sẵn
có trong lòng người dân lại trở thành những
vị hộ pháp, rộng truyền lẽ nhân quả. Chính
những lời giáo huấn của thần Bếp đối với Du
Tịnh Ý là một ví dụ hết sức điển hình. Vì thế,
sự thờ kính của Du Tịnh Ý đối với thần Bếp
đã không còn là một niềm tin mù quáng nữa,
mà nó trở thành một sức mạnh hỗ trợ vô cùng
hiệu quả trong việc giúp ông tránh ác làm
thiện. Vì tự thân ông không đủ sức _“một đao
dứt sạch”_ mọi vọng niệm tà ác, nên ông đã
nhờ đến niềm tin vào thần linh. Với ý tưởng
kiêng sợ vì lúc nào cũng có _“thần minh chứng
giám”_ , nên ông luôn có thể giữ mình trong
trạng thái tỉnh giác, không để cho những tâm
niệm xấu ác, tà vạy khởi lên và khống chế
mình.

Chúng ta cũng thấy được điều tương tự
trong _Liễu Phàm tứ huấn_ , khi Viên Liễu
Phàm mỗi đêm đều thắp hương kính cáo với
Thượng đế về những việc đã làm trong ngày.

Và kết quả tu thân mà cả hai người đạt
được đã chứng tỏ rằng phương tiện thích nghi
của giáo lý đạo Phật là hiệu quả. Điều tất
nhiên là một khi đã tiến sâu vào đạo Phật,
với trí tuệ sáng suốt hơn thì chắc chắn đến
một lúc nào đó tự họ sẽ nhận biết rõ ràng
về luật nhân quả đúng như lời Phật dạy mà
không còn cần thiết phải dựa vào niềm tin đối
với Thượng đế hay thần linh nữa.

Chúng ta có thể tin chắc rằng chính từ
quan điểm _“phương tiện thiện xảo”_ này mà
Đại sư Ấn Quang đã tán thành cũng như đích
thân cổ súy cho việc lưu hành các bản văn
khuyến thiện này. Cho dù chúng có pha tạp
đôi phần tín ngưỡng dân gian không thực sự
chân chính, nhưng với sức phương tiện dẫn
dắt của Chánh pháp, các bản văn này đã
mang lại lợi lạc cho rất nhiều người, nhất là
đối với đại đa số quần chúng bình dân mà
hầu hết đều không có nhiều tri thức.

Cho đến nay, giá trị khuyến thiện của
những bản văn này có thể nói là vẫn không
thay đổi. Những tâm niệm xấu ác tà vạy nằm
giấu kín trong lòng mỗi người vẫn luôn tồn
tại, và muốn chiến thắng được chúng để tu
sửa tự thân bao giờ cũng là việc hết sức khó
khăn. Vì vậy, những chia sẻ của người xưa
qua tập sách này chắc chắn vẫn là bài học
quý báu cho tất cả chúng ta trên con đường
nỗ lực hướng thiện.

Hơn thế nữa, những khó khăn mà chúng
ta phải đối mặt ngày nay trên con đường tu
sửa tự thân dường như cũng không khác
biệt mấy với người xưa. Tiên sinh Viên Liễu
Phàm đã mô tả điều đó như là sự _“quen theo
nếp cũ”_ :

_“... Người đời không ít kẻ thông minh tài
trí, nhưng sở dĩ không vun bồi phước đức cho
sâu dày, không phát triển nghiệp lành cho
rộng khắp, ấy chỉ vì một lẽ là quen theo nếp
cũ, do dự rụt rè, không đủ quyết tâm... ... nên
cứ thế mà mê đắm trôi qua hết một đời.”_

Và thần Bếp khi giáo huấn Du Đô cũng có
đoạn nói:

_“... Khi ông mở miệng buông lời, trong lòng
vẫn tự biết đang làm tổn thương đức tốt, chỉ
vì quen thói cũ... ... không thể dừng lại được.”_


_“Quen theo nếp cũ”_ hay _“quen thói cũ”_ đều
là căn bệnh chung của hầu hết mọi người.
Đạo Phật gọi những _“nếp cũ”_ này là tập khí
và dạy rằng phải nỗ lực dứt trừ thì mới có thể
đạt được thành tựu trên con đường tu tập.
Chúng ta có thể hình dung một cách đơn giản
về sự vận hành của tập khí như một chiếc xe
đã được khởi động nhưng rồi lại hoàn toàn
bị mất khả năng điều khiển. Vì thế, hướng
đi của chiếc xe chính là hướng đi trước đây,
và nó cứ thế mà lăn bánh, không thể thay
đổi. Đó là quán tính của một vật thể chuyển
động tự do. Khi không nhận thêm bất kỳ một
tác động chuyển hướng nào, nó sẽ tiếp tục di
chuyển theo hướng đã có.

Điều này có nghĩa là, nếu chúng ta đã
quen nói dối, có tập khí nói dối, thì việc tiếp
tục nói dối sẽ là một điều hoàn toàn tự nhiên,
không cần đến bất kỳ một sự nỗ lực, cố gắng
nào. Và cũng tương tự như thế với những thói
quen xấu khác như tham lam, trộm cắp, tà
dâm, uống rượu, ganh ghét, sân hận... Cho
nên, việc tu sửa tự thân luôn đòi hỏi nhiều nỗ
lực khó khăn, trong khi sự buông thả phóng
túng _“theo nếp cũ”_ lại nhấn chìm ta vào con
đường xấu ác mà không cần phải có sự cố
công gắng sức.

Chính vì thế, Khổng tử từng nói: _“Thắng
được người khác là có trí, thắng được chính
mình mới là người mạnh mẽ.”_ (Thắng nhân
giả trí, tự thắng giả cường.) Và trong kinh
Pháp cú, đức Phật dạy:

<div style="text-align: center">
> “Dù tại bãi chiến trường,  
> Thắng ngàn ngàn quân địch,  
> Tự thắng mình tốt hơn,  
> Thật chiến thắng tối thượng.”  
</div>

<div style="text-align: right">
Kinh Pháp cú, kệ số 103  
HT. Thích Minh Châu  
dịch từ bản Pali  
</div>

Tự thắng mình cũng chính là điều kiện tiên
quyết để tự lập số mạng, để chuyển họa thành
phúc. Vì thế, có thể nói rằng việc tự thắng mình
là mục tiêu chung của tất cả những ai muốn
hoàn thiện bản thân, muốn thay đổi cuộc đời
mình theo hướng tốt hơn. Và điểm khởi đầu cho
cuộc chiến đấu vượt qua chính mình như thế
đòi hỏi mỗi chúng ta phải tự nhận biết được
một cách khách quan và chính xác về tự thân
mình.

Tiên sinh Viên Liễu Phàm trong cuộc đối
thoại với Thiền sư Vân Cốc đã cho thấy ông
nhận biết khá rõ về những nhược điểm của
bản thân, những điều mà ông cho là nguyên
nhân đã khiến ông có một số mạng không tốt
đẹp. Thiền sư Vân Cốc đã tán thành những
nhận xét về tự thân của ông và hướng dẫn
phương thức để “cách mạng bản thân” như
sau:

_“... Nay ông đã biết rõ những điều sai trái
của mình... ... vậy ông phải hết lòng hối cải,
tự thay đổi... Hết thảy những việc từng làm
trước đây, xem như đã chết từ hôm qua. Hết
thảy những việc từ nay về sau, xem như mới
được sinh ra từ hôm nay.”_

Lời khuyên này cũng có thể áp dụng cho
tất cả những ai trong chúng ta đã có may
mắn nhận biết được sự sai trái của bản thân
mình. Đó chính là quyết tâm _“xóa đi làm lại”_
cuộc đời, đoạn tuyệt hoàn toàn với những sai
lầm của quá khứ và nỗ lực không ngừng nghỉ
trong việc xây dựng tương lai tươi đẹp hoàn
toàn mới.

Nhưng trường hợp của Du Tịnh Ý thì dường
như không được may mắn như thế. Ông chịu
đựng nhiều khổ đau nhưng không thấy được
nguyên nhân gây khổ đau, và vì thế không thể
hài lòng với những gì xảy đến cho mình. Ông
oán trời trách đất chính là vì không tự biết
được sai lầm của chính mình. Vì sao như vậy?
Bởi những tâm niệm xấu ác của ông hầu hết
đều được giấu kín trong lòng, chưa bộc lộ ra
ngoài. Vì thế, người đời có thể vẫn kính trọng
ông, xem ông như một bậc chính nhân quân
tử, đạo cao đức trọng... Và từ thái độ kính
trọng của người khác dành cho mình, ông đã
quay lại tự lừa dối bản thân khi tin rằng mình
_“không làm điều gì sai trái cả”_.

Trường hợp của Du Tịnh Ý dường như
cũng là trường hợp chung của rất nhiều người
trong chúng ta. Thật không dễ để tự mình
nhận biết những ý niệm sai lầm khi chúng
vẫn còn được che giấu kín trong lòng, chưa có
gì biểu lộ ra bên ngoài. Một người có thể chưa
phạm vào bất kỳ điều gì để người khác có thể
xem anh ta là kẻ tham lam, ích kỷ, dâm tà,
hung bạo... nhưng điều đó hoàn toàn không
đảm bảo anh ta thực sự là người đạo đức hoàn
thiện. Một cái nhìn kèm theo sự ưa thích khi
bắt gặp một người con gái đẹp, và tiếp đó là
một tâm niệm ham muốn chiếm hữu, có thể
không gây ra bất kỳ sự chú ý hoặc phê phán
nào từ những người chung quanh, nhưng
thực sự đã gieo mầm xấu ác. Nếu có những
ngoại duyên thích hợp, sẽ không ai dám chắc
rằng hạt nhân khởi điểm đó lại không tiếp tục
phát triển thành một lời tán tỉnh, trêu ghẹo,
cho đến lún sâu hơn nữa thành một hành vi
tội lỗi... Đối với những tâm niệm tham lam,
sân hận, ganh ghét, đố kỵ, cay độc, hiểm ác...
cũng đều như vậy. Chúng như những con rắn
độc ngủ yên và có vẻ như vô hại trong tâm
thức, nhưng luôn chờ dịp để vùng dậy và giết
chết mọi điều lành.

Điều đáng sợ nhất là chúng ta không tự
thấy được mối nguy hiểm tiềm tàng đó. Vì
thế, chúng ta thậm chí còn thỏa thích “dệt
mộng” với những tâm niệm xấu ác như tham
lam, tà dâm, oán hận... thay vì nỗ lực diệt
trừ chúng ngay khi vừa sinh khởi. Ta thích
thú với những ý niệm mơ tưởng về sắc dục,
hoặc những ý niệm oán hận người mà ta căm
ghét, hoặc mơ mộng việc có được những tài
sản không phải của ta... Và khi những điều
đó chưa biến thành hành vi thực sự, ta lại
hết sức ngây thơ khi tin rằng mình vẫn “hoàn
toàn vô tội”.

Vì thế, những lời giáo huấn của thần Bếp
không chỉ dành riêng cho Du Tịnh Ý, mà cũng
sẽ vô cùng quý báu nếu chúng ta biết vận
dụng để tự soi xét lại chính bản thân mình.
Trong câu chuyện về Vệ Trọng Đạt, bản văn
Liễu Phàm tứ huấn có dẫn lời Diêm chúa nói
rằng: _“Một niệm tà vạy khởi lên đã là xấu ác,
không đợi đến lúc ông thực sự làm.”_ Điều này
hoàn toàn đúng với trường hợp của Du Tịnh Ý
và cũng đúng với những tâm niệm xấu ác được
nuôi dưỡng ngấm ngầm của bất cứ ai.

Binh pháp xưa có câu: _“Biết người biết ta,
trăm trận trăm thắng.”_ Trong cuộc chiến đấu
vượt qua chính mình, chúng ta càng không thể
không tự biết mình. Tự mình phản tỉnh, xem
xét, phân tích và diệt trừ mọi tâm niệm xấu ác
đang từng lúc khởi sinh trong lòng mình chính
là phương thức quan trọng và hiệu quả nhất
để giúp ta có thể noi gương người xưa trong
việc chuyển họa thành phúc. Mong sao tất cả
những ai đọc qua sách này rồi đều sẽ làm được
điều đó.

<div style="text-align:right">
_Ngày đầu Xuân Ất Mùi (2015)_  
**Nguyễn Minh Tiến**
</div>
